Attribute VB_Name = "PRESTADORES"
Attribute VB_Base = "0{3372F4E9-ACBB-4C90-B692-611969EEC51C}{F88BC30B-381E-4A75-97CB-DB71E95DDFBF}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = False
Public PRECO_GESTAO As Double
Public PRECO_EMPREITEIRO As Double
Public PRECO_ELETRICISTA As Double
Public PRECO_ENCANADOR As Double
Public PRECO_PINTOR As Double
Public PRECO_INSTALADOR_AQUECEDOR As Double
Public VALOR_MINIMO_TERRAPLANAGEM As Double
Public PRECO_PAVIMENTACAO_EXTERNA As Double
Public PRECO_MURO_DIVISA As Double
Public PRECO_INSTALADOR_EQUIPAMENTOS_PISCINA As Double
Public PRECO_MURO_ARRIMO As Double



Private Sub UserForm_Initialize()

Call INICIAR

Windows("NOVO MODELO ORÇAMENTO.xlsm").Activate

Sheets("INPUT").Select

'PREÇOS

'GESTÃO
CP_AREA_CONSTRUIDA_EDIF = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_EDIF", Columns("A:B"), 2, False)

If CP_AREA_CONSTRUIDA_EDIF < 451 Then PRECO_GESTAO = 450
If CP_AREA_CONSTRUIDA_EDIF < 401 Then PRECO_GESTAO = 470
If CP_AREA_CONSTRUIDA_EDIF < 351 Then PRECO_GESTAO = 490
If CP_AREA_CONSTRUIDA_EDIF < 301 Then PRECO_GESTAO = 510
If CP_AREA_CONSTRUIDA_EDIF < 251 Then PRECO_GESTAO = 530
If CP_AREA_CONSTRUIDA_EDIF < 201 Then PRECO_GESTAO = 550
If CP_AREA_CONSTRUIDA_EDIF > 450 Then PRECO_GESTAO = 430

'DEMAIS PRESTADORES
PRECO_EMPREITEIRO = 1000 'm2 Área constrída
PRECO_ELETRICISTA = 80 'm2 Área constrída
PRECO_ENCANADOR = 60 'm2 Área constrída
PRECO_PINTOR = 100 'm2 Área constrída
PRECO_INSTALADOR_AQUECEDOR = 2000 'valor fixo
VALOR_MINIMO_TERRAPLANAGEM = 8000 'valor fixo
PRECO_PAVIMENTACAO_EXTERNA = 120 'm2 pavimentação
PRECO_MURO_DIVISA = 130 'm2 de muro
PRECO_INSTALADOR_EQUIPAMENTOS_PISCINA = 5000 'valor fixo
PRECO_MURO_ARRIMO = 250 'm2 de muro

On Error Resume Next

'EDIFICAÇÃO

If PRESTADORES.CP_PRESTADORES_EQUIPE_PEDREIROS_EDIF = 0 Or PRESTADORES.CP_PRESTADORES_EQUIPE_PEDREIROS_EDIF = "" Then
PRESTADORES.CP_PRESTADORES_EQUIPE_PEDREIROS_EDIF = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_EDIF", Columns("A:B"), 2, False) * PRECO_EMPREITEIRO
PRESTADORES.CP_PRESTADORES_EQUIPE_PEDREIROS_EDIF = Format(PRESTADORES.CP_PRESTADORES_EQUIPE_PEDREIROS_EDIF, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_ELETRICISTA = 0 Or PRESTADORES.CP_PRESTADORES_ELETRICISTA = "" Then
PRESTADORES.CP_PRESTADORES_ELETRICISTA = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_EDIF", Columns("A:B"), 2, False) * PRECO_ELETRICISTA
PRESTADORES.CP_PRESTADORES_ELETRICISTA = Format(PRESTADORES.CP_PRESTADORES_ELETRICISTA, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_ENCANADOR = 0 Or PRESTADORES.CP_PRESTADORES_ENCANADOR = "" Then
PRESTADORES.CP_PRESTADORES_ENCANADOR = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_EDIF", Columns("A:B"), 2, False) * PRECO_ENCANADOR
PRESTADORES.CP_PRESTADORES_ENCANADOR = Format(PRESTADORES.CP_PRESTADORES_ENCANADOR, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_PINTOR = 0 Or PRESTADORES.CP_PRESTADORES_PINTOR = "" Then
PRESTADORES.CP_PRESTADORES_PINTOR = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_EDIF", Columns("A:B"), 2, False) * PRECO_PINTOR
PRESTADORES.CP_PRESTADORES_PINTOR = Format(PRESTADORES.CP_PRESTADORES_PINTOR, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_INSTALADOR_AQUECEDORES = 0 Or PRESTADORES.CP_PRESTADORES_INSTALADOR_AQUECEDORES = "" Then
PRESTADORES.CP_PRESTADORES_INSTALADOR_AQUECEDORES = PRECO_INSTALADOR_AQUECEDOR
PRESTADORES.CP_PRESTADORES_INSTALADOR_AQUECEDORES = Format(PRESTADORES.CP_PRESTADORES_INSTALADOR_AQUECEDORES, "R$ #,##0.00")
End If



'SERVIÇOS EXTRAS

If PRESTADORES.CP_PRESTADORES_TERRAPLANAGEM = 0 Or PRESTADORES.CP_PRESTADORES_TERRAPLANAGEM = "" Then
PRESTADORES.CP_PRESTADORES_TERRAPLANAGEM = VALOR_MINIMO_TERRAPLANAGEM
PRESTADORES.CP_PRESTADORES_TERRAPLANAGEM = Format(PRESTADORES.CP_PRESTADORES_TERRAPLANAGEM, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_PAVIMENTAÇÃO_EXTERNA = 0 Or PRESTADORES.CP_PRESTADORES_PAVIMENTAÇÃO_EXTERNA = "" Then
PRESTADORES.CP_PRESTADORES_PAVIMENTAÇÃO_EXTERNA = WorksheetFunction.VLookup("CP_PAVIMENTACAO_EXTERNA", Columns("A:B"), 2, False) * PRECO_PAVIMENTACAO_EXTERNA
PRESTADORES.CP_PRESTADORES_PAVIMENTAÇÃO_EXTERNA = Format(PRESTADORES.CP_PRESTADORES_PAVIMENTAÇÃO_EXTERNA, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_MURO_DIVISA = 0 Or PRESTADORES.CP_PRESTADORES_MURO_DIVISA = "" Then
PRESTADORES.CP_PRESTADORES_MURO_DIVISA = WorksheetFunction.VLookup("CP_COMPRIMENTO_MURO_DIVISA", Columns("A:B"), 2, False) _
                                         * WorksheetFunction.VLookup("CP_ALTURA_MURO_DIVISA", Columns("A:B"), 2, False) * PRECO_MURO_DIVISA
PRESTADORES.CP_PRESTADORES_MURO_DIVISA = Format(PRESTADORES.CP_PRESTADORES_MURO_DIVISA, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_INSTALADOR_EQUIP_PISCINA = 0 Or PRESTADORES.CP_PRESTADORES_INSTALADOR_EQUIP_PISCINA = "" Then
PRESTADORES.CP_PRESTADORES_INSTALADOR_EQUIP_PISCINA = PRECO_INSTALADOR_EQUIPAMENTOS_PISCINA
PRESTADORES.CP_PRESTADORES_INSTALADOR_EQUIP_PISCINA = Format(PRESTADORES.CP_PRESTADORES_INSTALADOR_EQUIP_PISCINA, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_GESTAO_OBRA = 0 Or PRESTADORES.CP_PRESTADORES_GESTAO_OBRA = "" Then
PRESTADORES.CP_PRESTADORES_GESTAO_OBRA = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_EDIF", Columns("A:B"), 2, False) * PRECO_GESTAO
PRESTADORES.CP_PRESTADORES_GESTAO_OBRA = Format(PRESTADORES.CP_PRESTADORES_GESTAO_OBRA, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_PEDREIROS_PISCINA = 0 Or PRESTADORES.CP_PRESTADORES_PEDREIROS_PISCINA = "" Then
PRESTADORES.CP_PRESTADORES_PEDREIROS_PISCINA = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_PISCINA", Columns("G:H"), 2, False) * PRECO_EMPREITEIRO
PRESTADORES.CP_PRESTADORES_PEDREIROS_PISCINA = Format(PRESTADORES.CP_PRESTADORES_PEDREIROS_PISCINA, "R$ #,##0.00")
End If

If PRESTADORES.CP_PRESTADORES_MURO_ARRIMO = 0 Or PRESTADORES.CP_PRESTADORES_MURO_ARRIMO = "" Then
PRESTADORES.CP_PRESTADORES_MURO_ARRIMO = WorksheetFunction.VLookup("CP_COMPRIMENTO_ARRIMO", Columns("M:N"), 2, False) _
                                         * WorksheetFunction.VLookup("CP_ALTURA_ARRIMO", Columns("M:N"), 2, False) * PRECO_MURO_ARRIMO
PRESTADORES.CP_PRESTADORES_MURO_ARRIMO = Format(PRESTADORES.CP_PRESTADORES_MURO_ARRIMO, "R$ #,##0.00")
End If

On Error GoTo 0



End Sub

Private Sub SALVAR_PRESTADORES_Click()

Call INPUT_DADOS_PRESTADORES

End Sub
