Attribute VB_Name = "Z_DECLARAR_VARIAVEIS"

'ORDEM ETAPAS

Public ORD_INSTALACOES_OBRA_PROJETOS As Integer
Public ORD_FUNDACAO As Integer
Public ORD_ESGOTO_PLUVIAL_TERREO As Integer
Public ORD_CONTRAPISO_INTERNO_TERREO As Integer
Public ORD_PAREDES_TERREO As Integer
Public ORD_VIGA_RESPALDO_LAJE_TERREO  As Integer
Public ORD_PAREDES_PAV_1 As Integer
Public ORD_VIGA_RESPALDO_LAJE_PAV_1 As Integer
Public ORD_SUPRA_COBERTURA As Integer
Public ORD_COBERTURA As Integer
Public ORD_REBOCO As Integer
Public ORD_PINTURA As Integer
Public ORD_CONTRAPISO_EXTERNO As Integer
Public ORD_MURO_DIVISA As Integer
Public ORD_MURO_ARRIMO As Integer
Public ORD_PISCINA As Integer
Public ORD_PRESTADORES_SERVICOS As Integer
Public ORD_ESQUADRIAS As Integer


'PESOS FERROS
Public PESO_CA60_4MM As Double
Public PESO_CA50_5MM As Double
Public PESO_CA50_6MM As Double
Public PESO_CA50_8MM As Double
Public PESO_CA50_10MM As Double
Public PESO_CA50_12MM As Double
Public PESO_CA50_16MM As Double
Public PESO_CA60_5MM As Double



Sub DECLARAR_VARIAVEIS()

ORD_PRESTADORES_SERVICOS = 0
ORD_INSTALACOES_OBRA_PROJETOS = 1
ORD_FUNDACAO = 2
ORD_ESGOTO_PLUVIAL_TERREO = 3
ORD_CONTRAPISO_INTERNO_TERREO = 4
ORD_PAREDES_TERREO = 5
ORD_VIGA_RESPALDO_LAJE_TERREO = 6
ORD_PAREDES_PAV_1 = 7
ORD_VIGA_RESPALDO_LAJE_PAV_1 = 8
ORD_SUPRA_COBERTURA = 9
ORD_COBERTURA = 10
ORD_REBOCO = 11
ORD_PINTURA = 12
ORD_CONTRAPISO_EXTERNO = 13
ORD_MURO_DIVISA = 14
ORD_MURO_ARRIMO = 15
ORD_PISCINA = 16
ORD_ESQUADRIAS = 17


'PESOS FERROS

PESO_CA60_4MM = 1.31
PESO_CA50_5MM = 1.92
PESO_CA50_6MM = 3
PESO_CA50_8MM = 4.8
PESO_CA50_10MM = 7.56
PESO_CA50_12MM = 11.56
PESO_CA50_16MM = 18.94
PESO_CA60_5MM = 1.92



    
End Sub
