Attribute VB_Name = "ZZ_ATUALIZAR_CAMPOS"
'CAMPOS

'ARQ
Public CP_AREA_CONSTRUIDA_EDIF As Double
Public CP_M2_PAREDES_EDIF As Double
Public CP_M2_PAREDES_INTERNAS_EDIF As Double
Public CP_M2_PAREDES_EXTERNAS_EDIF As Double
Public CP_GABARITO_EDIF As Double
Public CP_PERIMETRO_PAREDES_TERREO_EDIF As Double
Public CP_TIPOLOGIA_EDIF As String

'ARQ TERREO
Public CP_AREA_M2_PAV_1_EDIF As Double
Public CP_M2_PAREDES_15_TERREO_EDIF As Double
Public CP_M2_PAREDES_20_TERREO_EDIF As Double
Public CP_M2_PAREDES_25_TERREO_EDIF As Double
Public CP_VAO_PORTAS_JANELAS_TERREO_EDIF As Double
Public CP_AREA_M2_TERREO_EDIF As Double

'ARQ LAJE TÉRREO
Public CP_AREA_LOJE_TERREO_EDIF As Double
Public CP_PERIMETRO_LOJE_TERREO_EDIF As Double
Public CP_AREA_LOJE_MACICA_TERREO_EDIF As Double

'ARQ PAV_1
Public CP_M2_PAREDES_15_PAV_1_EDIF As Double
Public CP_M2_PAREDES_20_PAV_1_EDIF As Double
Public CP_M2_PAREDES_25_PAV_1_EDIF As Double
Public CP_VAO_PORTAS_JANELAS_PAV_1_EDIF As Double
Public CP_PERIMETRO_PAREDES_PAV_1_EDIF As Double

'ARQ LAJE PAV_1
Public CP_PERIMETRO_LOJE_PAV_1_EDIF As Double
Public CP_AREA_LOJE_PAV_1_EDIF As Double
Public CP_AREA_LOJE_MACICA_PAV_1_EDIF As Double

'REVESTIMENTO
Public CP_REVESTIMENTO_INTERNO_EDIF As Double

'PAVIMENTAÇÃO EXTERNA
Public CP_PAVIMENTACAO_EXTERNA As Double
Public CP_PERIMETRO_PAV_EXTERNA As Double


'MURO DIVISA
Public CP_COMPRIMENTO_MURO_DIVISA As Double
Public CP_ALTURA_MURO_DIVISA As Double

'COBERTURA
Public CP_COBERTURA_1_EDIF As String
Public CP_COBERTURA_2_EDIF As String
Public CP_COBERTURA_3_EDIF As String
Public CP_COBERTURA_4_EDIF As String
Public CP_COBERTURA_5_EDIF As String
Public CP_COBERTURA_6_EDIF As String
Public CP_COBERTURA_7_EDIF As String
Public CP_COBERTURA_8_EDIF As String
Public CP_COBERTURA_9_EDIF As String
Public CP_COBERTURA_10_EDIF As String
Public CP_COBERTURA_11_EDIF As String
Public CP_COBERTURA_12_EDIF As String
Public CP_COBERTURA_13_EDIF As String
Public CP_COBERTURA_14_EDIF As String
Public CP_COBERTURA_15_EDIF As String
Public CP_COBERTURA_16_EDIF As String



Public CP_COMP_COBERTURA_1_EDIF As Double
Public CP_COMP_COBERTURA_2_EDIF As Double
Public CP_COMP_COBERTURA_3_EDIF As Double
Public CP_COMP_COBERTURA_4_EDIF As Double
Public CP_COMP_COBERTURA_5_EDIF As Double
Public CP_COMP_COBERTURA_6_EDIF As Double
Public CP_COMP_COBERTURA_7_EDIF As Double
Public CP_COMP_COBERTURA_8_EDIF As Double
Public CP_COMP_COBERTURA_9_EDIF As Double
Public CP_COMP_COBERTURA_10_EDIF As Double
Public CP_COMP_COBERTURA_11_EDIF As Double
Public CP_COMP_COBERTURA_12_EDIF As Double
Public CP_COMP_COBERTURA_13_EDIF As Double
Public CP_COMP_COBERTURA_14_EDIF As Double
Public CP_COMP_COBERTURA_15_EDIF As Double
Public CP_COMP_COBERTURA_16_EDIF As Double



Public CP_LARG_COBERTURA_1_EDIF As Double
Public CP_LARG_COBERTURA_2_EDIF As Double
Public CP_LARG_COBERTURA_3_EDIF As Double
Public CP_LARG_COBERTURA_4_EDIF As Double
Public CP_LARG_COBERTURA_5_EDIF As Double
Public CP_LARG_COBERTURA_6_EDIF As Double
Public CP_LARG_COBERTURA_7_EDIF As Double
Public CP_LARG_COBERTURA_8_EDIF As Double
Public CP_LARG_COBERTURA_9_EDIF As Double
Public CP_LARG_COBERTURA_10_EDIF As Double
Public CP_LARG_COBERTURA_11_EDIF As Double
Public CP_LARG_COBERTURA_12_EDIF As Double
Public CP_LARG_COBERTURA_13_EDIF As Double
Public CP_LARG_COBERTURA_14_EDIF As Double
Public CP_LARG_COBERTURA_15_EDIF As Double
Public CP_LARG_COBERTURA_16_EDIF As Double



Public CP_AGUAS_COBERTURA_1_EDIF As Double
Public CP_AGUAS_COBERTURA_2_EDIF As Double
Public CP_AGUAS_COBERTURA_3_EDIF As Double
Public CP_AGUAS_COBERTURA_4_EDIF As Double
Public CP_AGUAS_COBERTURA_5_EDIF As Double
Public CP_AGUAS_COBERTURA_6_EDIF As Double
Public CP_AGUAS_COBERTURA_7_EDIF As Double
Public CP_AGUAS_COBERTURA_8_EDIF As Double
Public CP_AGUAS_COBERTURA_9_EDIF As Double
Public CP_AGUAS_COBERTURA_10_EDIF As Double
Public CP_AGUAS_COBERTURA_11_EDIF As Double
Public CP_AGUAS_COBERTURA_12_EDIF As Double
Public CP_AGUAS_COBERTURA_13_EDIF As Double
Public CP_AGUAS_COBERTURA_14_EDIF As Double
Public CP_AGUAS_COBERTURA_15_EDIF As Double
Public CP_AGUAS_COBERTURA_16_EDIF As Double



Public CP_INCL_COBERTURA_1_EDIF As Double
Public CP_INCL_COBERTURA_2_EDIF As Double
Public CP_INCL_COBERTURA_3_EDIF As Double
Public CP_INCL_COBERTURA_4_EDIF As Double
Public CP_INCL_COBERTURA_5_EDIF As Double
Public CP_INCL_COBERTURA_6_EDIF As Double
Public CP_INCL_COBERTURA_7_EDIF As Double
Public CP_INCL_COBERTURA_8_EDIF As Double
Public CP_INCL_COBERTURA_9_EDIF As Double
Public CP_INCL_COBERTURA_10_EDIF As Double
Public CP_INCL_COBERTURA_11_EDIF As Double
Public CP_INCL_COBERTURA_12_EDIF As Double
Public CP_INCL_COBERTURA_13_EDIF As Double
Public CP_INCL_COBERTURA_14_EDIF As Double
Public CP_INCL_COBERTURA_15_EDIF As Double
Public CP_INCL_COBERTURA_16_EDIF As Double



'ENGENHARIA
Public CP_RESISTENCIA_CONCRETO_EDIF As String
Public CP_DIAMETRO_ESTACAS_EDIF As String
Public CP_PROF_ESTACAS_EDIF As Double
Public CP_QTD_ESTACAS_EDIF As Double

'AÇO ESTACAS
Public CP_CA60_4MM_EST_EDIF As Double
Public CP_CA50_5MM_EST_EDIF As Double
Public CP_CA50_6MM_EST_EDIF As Double
Public CP_CA50_8MM_EST_EDIF As Double
Public CP_CA50_10MM_EST_EDIF As Double
Public CP_CA50_12MM_EST_EDIF As Double
Public CP_CA50_16MM_EST_EDIF As Double
Public CP_CA60_5MM_EST_EDIF As Double
Public CP_CONCR_EST_EDIF As Double

'AÇO SAPATAS
Public CP_CA60_4MM_SAP_EDIF As Double
Public CP_CA50_5MM_SAP_EDIF As Double
Public CP_CA50_6MM_SAP_EDIF As Double
Public CP_CA50_8MM_SAP_EDIF As Double
Public CP_CA50_10MM_SAP_EDIF As Double
Public CP_CA50_12MM_SAP_EDIF As Double
Public CP_CA50_16MM_SAP_EDIF As Double
Public CP_CA60_5MM_SAP_EDIF As Double
Public CP_CONCR_SAP_EDIF As Double

'AÇO ARRANQUES
Public CP_CA60_4MM_ARR_EDIF As Double
Public CP_CA50_5MM_ARR_EDIF As Double
Public CP_CA50_6MM_ARR_EDIF As Double
Public CP_CA50_8MM_ARR_EDIF As Double
Public CP_CA50_10MM_ARR_EDIF As Double
Public CP_CA50_12MM_ARR_EDIF As Double
Public CP_CA50_16MM_ARR_EDIF As Double
Public CP_CA60_5MM_ARR_EDIF As Double
Public CP_CONCR_ARR_EDIF As Double

'AÇO BALDRAMES
Public CP_CA60_4MM_BALD_EDIF As Double
Public CP_CA50_5MM_BALD_EDIF As Double
Public CP_CA50_6MM_BALD_EDIF As Double
Public CP_CA50_8MM_BALD_EDIF As Double
Public CP_CA50_10MM_BALD_EDIF As Double
Public CP_CA50_12MM_BALD_EDIF As Double
Public CP_CA50_16MM_BALD_EDIF As Double
Public CP_CA60_5MM_BALD_EDIF As Double
Public CP_CONCR_BALD_EDIF As Double

'AÇO COLUNAS TÉRREO
Public CP_CA60_4MM_COLUNA_TERREO_EDIF As Double
Public CP_CA50_5MM_COLUNA_TERREO_EDIF As Double
Public CP_CA50_6MM_COLUNA_TERREO_EDIF As Double
Public CP_CA50_8MM_COLUNA_TERREO_EDIF As Double
Public CP_CA50_10MM_COLUNA_TERREO_EDIF As Double
Public CP_CA50_12MM_COLUNA_TERREO_EDIF As Double
Public CP_CA50_16MM_COLUNA_TERREO_EDIF As Double
Public CP_CA60_5MM_COLUNA_TERREO_EDIF As Double
Public CP_CONCR_COLUNA_TERREO_EDIF As Double

'CAIXARIAS PILARES TÉRREO
Public CP_COLUNAS_15_TERREO_EDIF As Double
Public CP_COLUNAS_20_TERREO_EDIF As Double
Public CP_COLUNAS_30_TERREO_EDIF As Double
Public CP_AREA_FORMA_COLUNA_MAIOR_25CM As Double

'VIGA RESPALDO TÉRREO
Public CP_CA60_4MM_VIGA_RESPALDO_TERREO_EDIF As Double
Public CP_CA50_5MM_VIGA_RESPALDO_TERREO_EDIF As Double
Public CP_CA50_6MM_VIGA_RESPALDO_TERREO_EDIF As Double
Public CP_CA50_8MM_VIGA_RESPALDO_TERREO_EDIF As Double
Public CP_CA50_10MM_VIGA_RESPALDO_TERREO_EDIF As Double
Public CP_CA50_12MM_VIGA_RESPALDO_TERREO_EDIF As Double
Public CP_CA50_16MM_VIGA_RESPALDO_TERREO_EDIF As Double
Public CP_CA60_5MM_VIGA_RESPALDO_TERREO_EDIF As Double
Public CP_CONCR_VIGA_RESPALDO_TERREO_EDIF As Double

'LAJE TÉRREO
Public CP_TIPO_LOJE_TERREO_EDIF As String
Public CP_RESIST_CONCRETO_LOJE_TERREO_EDIF As String

'AÇO COLUNAS PAV_1
Public CP_CA60_4MM_COLUN_PAV_1_EDIF As Double
Public CP_CA50_5MM_COLUN_PAV_1_EDIF As Double
Public CP_CA50_6MM_COLUN_PAV_1_EDIF As Double
Public CP_CA50_8MM_COLUN_PAV_1_EDIF As Double
Public CP_CA50_10MM_COLUN_PAV_1_EDIF As Double
Public CP_CA50_12MM_COLUN_PAV_1_EDIF As Double
Public CP_CA50_16MM_COLUN_PAV_1_EDIF As Double
Public CP_CA60_5MM_COLUN_PAV_1_EDIF As Double
Public CP_CONCR_COLUN_PAV_1_EDIF As Double

'CAIXARIA COLUNAS PAV_1
Public CP_COLUNAS_15_PAV_1_EDIF As Double
Public CP_COLUNAS_20_PAV_1_EDIF As Double
Public CP_COLUNAS_25_PAV_1_EDIF As Double
Public CP_AREA_FORMA_COLUNA_PAV_1_MAIOR_25CM As Double

'AÇO VIGAS PAV_1
Public CP_CA60_4MM_VIGA_RESPALDO_PAV_1_EDIF As Double
Public CP_CA50_5MM_VIGA_RESPALDO_PAV_1_EDIF As Double
Public CP_CA50_6MM_VIGA_RESPALDO_PAV_1_EDIF As Double
Public CP_CA50_8MM_VIGA_RESPALDO_PAV_1_EDIF As Double
Public CP_CA50_10MM_VIGA_RESPALDO_PAV_1_EDIF As Double
Public CP_CA50_12MM_VIGA_RESPALDO_PAV_1_EDIF As Double
Public CP_CA50_16MM_VIGA_RESPALDO_PAV_1_EDIF As Double
Public CP_CA60_5MM_VIGA_RESPALDO_PAV_1_EDIF As Double
Public CP_VOLUME_CONCRETO_VIGA_RESPALDO_PAV_1_EDIF As Double

'LAJE PAV_1
Public CP_TIPO_LOJE_PAV_1_EDIF As String
Public CP_RESIST_CONCRETO_LOJE_PAV_1_EDIF As String

'COLUNAS COBERTURA
Public CP_CA60_4MM_COLUNA_COBERTURA_EDIF As Double
Public CP_CA50_5MM_COLUNA_COBERTURA_EDIF As Double
Public CP_CA50_6MM_COLUNA_COBERTURA_EDIF As Double
Public CP_CA50_8MM_COLUNA_COBERTURA_EDIF As Double
Public CP_CA50_10MM_COLUNA_COBERTURA_EDIF As Double
Public CP_CA50_12MM_COLUNA_COBERTURA_EDIF As Double
Public CP_CA50_16MM_COLUNA_COBERTURA_EDIF As Double
Public CP_CA60_5MM_COLUNA_COBERTURA_EDIF As Double
Public CP_VOLUME_CONCRETO_COLUNA_RESPALDO_COBERTURA_EDIF As Double

'VIGAS COBERTURAS
Public CP_CA60_4MM_VIGA_COBERTURA_EDIF As Double
Public CP_CA50_5MM_VIGA_COBERTURA_EDIF As Double
Public CP_CA50_6MM_VIGA_COBERTURA_EDIF As Double
Public CP_CA50_8MM_VIGA_COBERTURA_EDIF As Double
Public CP_CA50_10MM_VIGA_COBERTURA_EDIF As Double
Public CP_CA50_12MM_VIGA_COBERTURA_EDIF As Double
Public CP_CA50_16MM_VIGA_COBERTURA_EDIF As Double
Public CP_CA60_5MM_VIGA_COBERTURA_EDIF As Double
Public CP_VOLUME_CONCRETO_VIGA_RESPALDO_COBERTURA_EDIF As Double

'CAIXARIAS COBERTURA
Public CP_COLUNAS_15_COBERTURA_EDIF As Double
Public CP_COLUNAS_20_COBERTURA_EDIF As Double
Public CP_COLUNAS_25_COBERTURA_EDIF As Double
Public CP_AREA_FORMA_COLUNA_COBERTURA_MAIOR_25CM As Double

'MURO ARRIMO
Public CP_COMPRIMENTO_ARRIMO As Double
Public CP_ALTURA_ARRIMO As Double
Public CP_NUMERO_VIGAS_ARRIMO As Double
Public CP_QTD_ESTACAS_ARRIMO As Double
Public CP_PROF_ESTACAS_ARRIMO As Double
Public CP_DIAMETRO_ESTACAS_ARRIMO As Double
Public CP_COLUNAS_15_ARRIMO As Double
Public CP_COLUNAS_20_ARRIMO As Double
Public CP_COLUNAS_30_ARRIMO As Double
Public CP_AREA_FORMA_COLUNA_ARRIMO_MAIOR_25CM As Double
Public CP_CA60_4MM_ESTACAS_ARRIMO As Double
Public CP_CA50_5MM_ESTACAS_ARRIMO As Double
Public CP_CA50_6MM_ESTACAS_ARRIMO As Double
Public CP_CA50_8MM_ESTACAS_ARRIMO As Double
Public CP_CA50_10MM_ESTACAS_ARRIMO As Double
Public CP_CA50_12MM_ESTACAS_ARRIMO As Double
Public CP_CA50_16MM_ESTACAS_ARRIMO As Double
Public CP_CA60_5MM_ESTACAS_ARRIMO As Double
Public CP_CONCR_ESTACAS_ARRIMO As Double
Public CP_CA60_4MM_SAPATAS_ARRIMO As Double
Public CP_CA50_5MM_SAPATAS_ARRIMO As Double
Public CP_CA50_6MM_SAPATAS_ARRIMO As Double
Public CP_CA50_8MM_SAPATAS_ARRIMO As Double
Public CP_CA50_10MM_SAPATAS_ARRIMO As Double
Public CP_CA50_12MM_SAPATAS_ARRIMO As Double
Public CP_CA50_16MM_SAPATAS_ARRIMO As Double
Public CP_CA60_5MM_SAPATAS_ARRIMO As Double
Public CP_CONCR_SAPATAS_ARRIMO As Double
Public CP_CA60_4MM_ARRANQUES_ARRIMO As Double
Public CP_CA50_5MM_ARRANQUES_ARRIMO As Double
Public CP_CA50_6MM_ARRANQUES_ARRIMO As Double
Public CP_CA50_8MM_ARRANQUES_ARRIMO As Double
Public CP_CA50_10MM_ARRANQUES_ARRIMO As Double
Public CP_CA50_12MM_ARRANQUES_ARRIMO As Double
Public CP_CA50_16MM_ARRANQUES_ARRIMO As Double
Public CP_CA60_5MM_ARRANQUES_ARRIMO As Double
Public CP_CONCR_ARRANQUES_ARRIMO As Double
Public CP_CA60_4MM_BALDRAME_ARRIMO As Double
Public CP_CA50_5MM_BALDRAME_ARRIMO As Double
Public CP_CA50_6MM_BALDRAME_ARRIMO As Double
Public CP_CA50_8MM_BALDRAME_ARRIMO As Double
Public CP_CA50_10MM_BALDRAME_ARRIMO As Double
Public CP_CA50_12MM_BALDRAME_ARRIMO As Double
Public CP_CA50_16MM_BALDRAME_ARRIMO As Double
Public CP_CA60_5MM_BALDRAME_ARRIMO As Double
Public CP_CONCR_BALDRAME_ARRIMO As Double
Public CP_CA60_4MM_GIGANTE_ARRIMO As Double
Public CP_CA50_5MM_GIGANTE_ARRIMO As Double
Public CP_CA50_6MM_GIGANTE_ARRIMO As Double
Public CP_CA50_8MM_GIGANTE_ARRIMO As Double
Public CP_CA50_10MM_GIGANTE_ARRIMO As Double
Public CP_CA50_12MM_GIGANTE_ARRIMO As Double
Public CP_CA50_16MM_GIGANTE_ARRIMO As Double
Public CP_CA60_5MM_GIGANTE_ARRIMO As Double
Public CP_CONCR_GIGANTE_ARRIMO As Double
Public CP_CA60_4MM_COLUNAS_ARRIMO As Double
Public CP_CA50_5MM_COLUNAS_ARRIMO As Double
Public CP_CA50_6MM_COLUNAS_ARRIMO As Double
Public CP_CA50_8MM_COLUNAS_ARRIMO As Double
Public CP_CA50_10MM_COLUNAS_ARRIMO As Double
Public CP_CA50_12MM_COLUNAS_ARRIMO As Double
Public CP_CA50_16MM_COLUNAS_ARRIMO As Double
Public CP_CA60_5MM_COLUNAS_ARRIMO As Double
Public CP_CONCR_COLUNAS_ARRIMO As Double
Public CP_CA60_4MM_VIGAS_ARRIMO As Double
Public CP_CA50_5MM_VIGAS_ARRIMO As Double
Public CP_CA50_6MM_VIGAS_ARRIMO As Double
Public CP_CA50_8MM_VIGAS_ARRIMO As Double
Public CP_CA50_10MM_VIGAS_ARRIMO As Double
Public CP_CA50_12MM_VIGAS_ARRIMO As Double
Public CP_CA50_16MM_VIGAS_ARRIMO As Double
Public CP_CA60_5MM_VIGAS_ARRIMO As Double
Public CP_CONCR_VIGAS_ARRIMO As Double
Public CP_RESISTENCIA_CONCRETO_ARRIMO As String

'PISCINA

Public CP_AREA_CONSTRUIDA_PISCINA As Double
Public CP_PAREDES_M2_TOTAL_PISCINA As Double
Public CP_PERIMETRO_PAREDES_PISCINA As Double
Public CP_GABARITO_OBRA_PISCINA As Double
Public CP_PROFUNDIDADE_PISCINA As Double
Public CP_QTD_ESTACAS_PISCINA As Double
Public CP_DIAMETRO_ESTACAS_PISCINA As Double
Public CP_PROFUNDIDADE_ESTACAS_PISCINA As Double
Public CP_COLUNAS_15_PISCINA As Double
Public CP_COLUNAS_20_PISCINA As Double
Public CP_COLUNAS_25_PISCINA As Double
Public CP_AREA_FORMA_COLUNA_MAIOR_25CM_PISCINA As Double
Public CP_RESISTENCIA_CONCRETO_PISCINA As String


Public CP_CA60_4MM_ESTACAS_PISCINA As Double
Public CP_CA50_5MM_ESTACAS_PISCINA As Double
Public CP_CA50_6MM_ESTACAS_PISCINA As Double
Public CP_CA50_8MM_ESTACAS_PISCINA As Double
Public CP_CA50_10MM_ESTACAS_PISCINA As Double
Public CP_CA50_12MM_ESTACAS_PISCINA As Double
Public CP_CA50_16MM_ESTACAS_PISCINA As Double
Public CP_CA60_5MM_ESTACAS_PISCINA As Double
Public CP_CONCR_ESTACAS_PISCINA As Double

Public CP_CA60_4MM_SAPATAS_PISCINA As Double
Public CP_CA50_5MM_SAPATAS_PISCINA As Double
Public CP_CA50_6MM_SAPATAS_PISCINA As Double
Public CP_CA50_8MM_SAPATAS_PISCINA As Double
Public CP_CA50_10MM_SAPATAS_PISCINA As Double
Public CP_CA50_12MM_SAPATAS_PISCINA As Double
Public CP_CA50_16MM_SAPATAS_PISCINA As Double
Public CP_CA60_5MM_SAPATAS_PISCINA As Double
 Public CP_CONCR_SAPATAS_PISCINA As Double

Public CP_CA60_4MM_ARRANQUES_PISCINA As Double
Public CP_CA50_5MM_ARRANQUES_PISCINA As Double
Public CP_CA50_6MM_ARRANQUES_PISCINA As Double
Public CP_CA50_8MM_ARRANQUES_PISCINA As Double
Public CP_CA50_10MM_ARRANQUES_PISCINA As Double
Public CP_CA50_12MM_ARRANQUES_PISCINA As Double
Public CP_CA50_16MM_ARRANQUES_PISCINA As Double
Public CP_CA60_5MM_ARRANQUES_PISCINA As Double
Public CP_CONCR_ARRANQUES_PISCINA As Double

Public CP_CA60_4MM_BALDRAME_PISCINA As Double
Public CP_CA50_5MM_BALDRAME_PISCINA As Double
Public CP_CA50_6MM_BALDRAME_PISCINA As Double
Public CP_CA50_8MM_BALDRAME_PISCINA As Double
Public CP_CA50_10MM_BALDRAME_PISCINA As Double
Public CP_CA50_12MM_BALDRAME_PISCINA As Double
Public CP_CA50_16MM_BALDRAME_PISCINA As Double
Public CP_CA60_5MM_BALDRAME_PISCINA As Double
Public CP_CONCR_BALDRAME_PISCINA As Double

Public CP_CA60_4MM_CONTRAPISO_PISCINA As Double
Public CP_CA50_5MM_CONTRAPISO_PISCINA As Double
Public CP_CA50_6MM_CONTRAPISO_PISCINA As Double
Public CP_CA50_8MM_CONTRAPISO_PISCINA As Double
Public CP_CA50_10MM_CONTRAPISO_PISCINA As Double
Public CP_CA50_12MM_CONTRAPISO_PISCINA As Double
Public CP_CA50_16MM_CONTRAPISO_PISCINA As Double
Public CP_CA60_5MM_CONTRAPISO_PISCINA As Double
Public CP_CONCR_GIGANTE_PISCINA As Double

Public CP_CA60_4MM_COLUNAS_PISCINA As Double
Public CP_CA50_5MM_COLUNAS_PISCINA As Double
Public CP_CA50_6MM_COLUNAS_PISCINA As Double
Public CP_CA50_8MM_COLUNAS_PISCINA As Double
Public CP_CA50_10MM_COLUNAS_PISCINA As Double
Public CP_CA50_12MM_COLUNAS_PISCINA As Double
Public CP_CA50_16MM_COLUNAS_PISCINA As Double
Public CP_CA60_5MM_COLUNAS_PISCINA As Double
Public CP_CONCR_COLUNAS_PISCINA As Double

Public CP_CA60_4MM_VIGAS_PISCINA As Double
Public CP_CA50_5MM_VIGAS_PISCINA As Double
Public CP_CA50_6MM_VIGAS_PISCINA As Double
Public CP_CA50_8MM_VIGAS_PISCINA As Double
Public CP_CA50_10MM_VIGAS_PISCINA As Double
Public CP_CA50_12MM_VIGAS_PISCINA As Double
Public CP_CA50_16MM_VIGAS_PISCINA As Double
Public CP_CA60_5MM_VIGAS_PISCINA As Double
Public CP_CONCR_VIGAS_PISCINA As Double

'ESQUADRIAS
 
 Public CP_ESQUADRIA_TIPO_1 As String
 Public CP_ESQUADRIA_TIPO_2 As String
 Public CP_ESQUADRIA_TIPO_3 As String
 Public CP_ESQUADRIA_TIPO_4 As String
 Public CP_ESQUADRIA_TIPO_5 As String
 Public CP_ESQUADRIA_TIPO_6 As String
 Public CP_ESQUADRIA_TIPO_7 As String
 Public CP_ESQUADRIA_TIPO_8 As String
 Public CP_ESQUADRIA_TIPO_9 As String
 Public CP_ESQUADRIA_TIPO_10 As String
 Public CP_ESQUADRIA_TIPO_11 As String
 Public CP_ESQUADRIA_TIPO_12 As String
 Public CP_ESQUADRIA_TIPO_13 As String
 Public CP_ESQUADRIA_TIPO_14 As String
 Public CP_ESQUADRIA_TIPO_15 As String
 Public CP_ESQUADRIA_TIPO_16 As String
 Public CP_ESQUADRIA_TIPO_17 As String
 Public CP_ESQUADRIA_TIPO_18 As String
 
 Public CP_TELA_1 As String
 Public CP_TELA_2 As String
 Public CP_TELA_3 As String
 Public CP_TELA_4 As String
 Public CP_TELA_5 As String
 Public CP_TELA_6 As String
 Public CP_TELA_7 As String
 Public CP_TELA_8 As String
 Public CP_TELA_9 As String
 Public CP_TELA_10 As String
 Public CP_TELA_11 As String
 Public CP_TELA_12 As String
 Public CP_TELA_13 As String
 Public CP_TELA_14 As String
 Public CP_TELA_15 As String
 Public CP_TELA_16 As String
 Public CP_TELA_17 As String
 Public CP_TELA_18 As String


 Public CP_QTD_1 As Double
 Public CP_QTD_2 As Double
 Public CP_QTD_3 As Double
 Public CP_QTD_4 As Double
 Public CP_QTD_5 As Double
 Public CP_QTD_6 As Double
 Public CP_QTD_7 As Double
 Public CP_QTD_8 As Double
 Public CP_QTD_9 As Double
 Public CP_QTD_10 As Double
 Public CP_QTD_11 As Double
 Public CP_QTD_12 As Double
 Public CP_QTD_13 As Double
 Public CP_QTD_14 As Double
 Public CP_QTD_15 As Double
 Public CP_QTD_16 As Double
 Public CP_QTD_17 As Double
 Public CP_QTD_18 As Double
  
 Public CP_ALTURA_1 As Double
 Public CP_ALTURA_2 As Double
 Public CP_ALTURA_3 As Double
 Public CP_ALTURA_4 As Double
 Public CP_ALTURA_5 As Double
 Public CP_ALTURA_6 As Double
 Public CP_ALTURA_7 As Double
 Public CP_ALTURA_8 As Double
 Public CP_ALTURA_9 As Double
 Public CP_ALTURA_10 As Double
 Public CP_ALTURA_11 As Double
 Public CP_ALTURA_12 As Double
 Public CP_ALTURA_13 As Double
 Public CP_ALTURA_14 As Double
 Public CP_ALTURA_15 As Double
 Public CP_ALTURA_16 As Double
 Public CP_ALTURA_17 As Double
 Public CP_ALTURA_18 As Double
 
 Public CP_LARGURA_1 As Double
 Public CP_LARGURA_2 As Double
 Public CP_LARGURA_3 As Double
 Public CP_LARGURA_4 As Double
 Public CP_LARGURA_5 As Double
 Public CP_LARGURA_6 As Double
 Public CP_LARGURA_7 As Double
 Public CP_LARGURA_8 As Double
 Public CP_LARGURA_9 As Double
 Public CP_LARGURA_10 As Double
 Public CP_LARGURA_11 As Double
 Public CP_LARGURA_12 As Double
 Public CP_LARGURA_13 As Double
 Public CP_LARGURA_14 As Double
 Public CP_LARGURA_15 As Double
 Public CP_LARGURA_16 As Double
 Public CP_LARGURA_17 As Double
 Public CP_LARGURA_18 As Double
 
 Public CP_FOLHAS_1 As Double
 Public CP_FOLHAS_2 As Double
 Public CP_FOLHAS_3 As Double
 Public CP_FOLHAS_4 As Double
 Public CP_FOLHAS_5 As Double
 Public CP_FOLHAS_6 As Double
 Public CP_FOLHAS_7 As Double
 Public CP_FOLHAS_8 As Double
 Public CP_FOLHAS_9 As Double
 Public CP_FOLHAS_10 As Double
 Public CP_FOLHAS_11 As Double
 Public CP_FOLHAS_12 As Double
 Public CP_FOLHAS_13 As Double
 Public CP_FOLHAS_14 As Double
 Public CP_FOLHAS_15 As Double
 Public CP_FOLHAS_16 As Double
 Public CP_FOLHAS_17 As Double
 Public CP_FOLHAS_18 As Double

   


Sub ATUALIZAR_CAMPOS()


Windows("NOVO MODELO ORÇAMENTO.xlsm").Activate
Sheets("INPUT").Select

'ARQ
CP_AREA_CONSTRUIDA_EDIF = 0
CP_M2_PAREDES_EDIF = 0
CP_M2_PAREDES_INTERNAS_EDIF = 0
CP_M2_PAREDES_EXTERNAS_EDIF = 0
CP_GABARITO_EDIF = 0
CP_PERIMETRO_PAREDES_TERREO_EDIF = 0
CP_TIPOLOGIA_EDIF = ""
'TÉRREO
CP_M2_PAREDES_15_TERREO_EDIF = 0
CP_M2_PAREDES_20_TERREO_EDIF = 0
CP_M2_PAREDES_25_TERREO_EDIF = 0
CP_VAO_PORTAS_JANELAS_TERREO_EDIF = 0
CP_AREA_M2_TERREO_EDIF = 0
'LAJE TÉRREO
CP_AREA_LOJE_TERREO_EDIF = 0
CP_PERIMETRO_LOJE_TERREO_EDIF = 0
CP_AREA_LOJE_MACICA_TERREO_EDIF = 0
'PAV_1
CP_AREA_M2_PAV_1_EDIF = 0
CP_M2_PAREDES_15_PAV_1_EDIF = 0
CP_M2_PAREDES_20_PAV_1_EDIF = 0
CP_M2_PAREDES_25_PAV_1_EDIF = 0
CP_VAO_PORTAS_JANELAS_PAV_1_EDIF = 0
CP_PERIMETRO_PAREDES_PAV_1_EDIF = 0
CP_PERIMETRO_LOJE_PAV_1_EDIF = 0
'LAJE PAV 1
CP_AREA_LOJE_PAV_1_EDIF = 0
CP_AREA_LOJE_MACICA_PAV_1_EDIF = 0
'REVESTIMENTO
CP_REVESTIMENTO_INTERNO_EDIF = 0
'PAVIMENTAÇÃO EXTERNA
CP_PAVIMENTACAO_EXTERNA = 0
CP_PERIMETRO_PAV_EXTERNA = 0
'MURO DIVISA
CP_COMPRIMENTO_MURO_DIVISA = 0
CP_ALTURA_MURO_DIVISA = 0
'COBERTURA
CP_COBERTURA_1_EDIF = 0
CP_COBERTURA_2_EDIF = 0
CP_COBERTURA_3_EDIF = 0
CP_COBERTURA_4_EDIF = 0
CP_COBERTURA_5_EDIF = 0
CP_COBERTURA_6_EDIF = 0
CP_COBERTURA_7_EDIF = 0
CP_COBERTURA_8_EDIF = 0
CP_COBERTURA_9_EDIF = 0
CP_COBERTURA_10_EDIF = 0
CP_COBERTURA_11_EDIF = 0
CP_COBERTURA_12_EDIF = 0
CP_COBERTURA_13_EDIF = 0
CP_COBERTURA_14_EDIF = 0
CP_COBERTURA_15_EDIF = 0
CP_COBERTURA_16_EDIF = 0


CP_COMP_COBERTURA_1_EDIF = 0
CP_COMP_COBERTURA_2_EDIF = 0
CP_COMP_COBERTURA_3_EDIF = 0
CP_COMP_COBERTURA_4_EDIF = 0
CP_COMP_COBERTURA_5_EDIF = 0
CP_COMP_COBERTURA_6_EDIF = 0
CP_COMP_COBERTURA_7_EDIF = 0
CP_COMP_COBERTURA_8_EDIF = 0
CP_COMP_COBERTURA_9_EDIF = 0
CP_COMP_COBERTURA_10_EDIF = 0
CP_COMP_COBERTURA_11_EDIF = 0
CP_COMP_COBERTURA_12_EDIF = 0
CP_COMP_COBERTURA_13_EDIF = 0
CP_COMP_COBERTURA_14_EDIF = 0
CP_COMP_COBERTURA_15_EDIF = 0
CP_COMP_COBERTURA_16_EDIF = 0

CP_LARG_COBERTURA_1_EDIF = 0
CP_LARG_COBERTURA_2_EDIF = 0
CP_LARG_COBERTURA_3_EDIF = 0
CP_LARG_COBERTURA_4_EDIF = 0
CP_LARG_COBERTURA_5_EDIF = 0
CP_LARG_COBERTURA_6_EDIF = 0
CP_LARG_COBERTURA_7_EDIF = 0
CP_LARG_COBERTURA_8_EDIF = 0
CP_LARG_COBERTURA_9_EDIF = 0
CP_LARG_COBERTURA_10_EDIF = 0
CP_LARG_COBERTURA_11_EDIF = 0
CP_LARG_COBERTURA_12_EDIF = 0
CP_LARG_COBERTURA_13_EDIF = 0
CP_LARG_COBERTURA_14_EDIF = 0
CP_LARG_COBERTURA_15_EDIF = 0
CP_LARG_COBERTURA_16_EDIF = 0


CP_AGUAS_COBERTURA_1_EDIF = 0
CP_AGUAS_COBERTURA_2_EDIF = 0
CP_AGUAS_COBERTURA_3_EDIF = 0
CP_AGUAS_COBERTURA_4_EDIF = 0
CP_AGUAS_COBERTURA_5_EDIF = 0
CP_AGUAS_COBERTURA_6_EDIF = 0
CP_AGUAS_COBERTURA_7_EDIF = 0
CP_AGUAS_COBERTURA_8_EDIF = 0
CP_AGUAS_COBERTURA_9_EDIF = 0
CP_AGUAS_COBERTURA_10_EDIF = 0
CP_AGUAS_COBERTURA_11_EDIF = 0
CP_AGUAS_COBERTURA_12_EDIF = 0
CP_AGUAS_COBERTURA_13_EDIF = 0
CP_AGUAS_COBERTURA_14_EDIF = 0
CP_AGUAS_COBERTURA_15_EDIF = 0
CP_AGUAS_COBERTURA_16_EDIF = 0



CP_INCL_COBERTURA_1_EDIF = 0
CP_INCL_COBERTURA_2_EDIF = 0
CP_INCL_COBERTURA_3_EDIF = 0
CP_INCL_COBERTURA_4_EDIF = 0
CP_INCL_COBERTURA_5_EDIF = 0
CP_INCL_COBERTURA_6_EDIF = 0
CP_INCL_COBERTURA_7_EDIF = 0
CP_INCL_COBERTURA_8_EDIF = 0
CP_INCL_COBERTURA_9_EDIF = 0
CP_INCL_COBERTURA_10_EDIF = 0
CP_INCL_COBERTURA_11_EDIF = 0
CP_INCL_COBERTURA_12_EDIF = 0
CP_INCL_COBERTURA_13_EDIF = 0
CP_INCL_COBERTURA_14_EDIF = 0
CP_INCL_COBERTURA_15_EDIF = 0
CP_INCL_COBERTURA_16_EDIF = 0




'ENGENHARIA
CP_RESISTENCIA_CONCRETO_EDIF = ""
CP_DIAMETRO_ESTACAS_EDIF = ""
CP_PROF_ESTACAS_EDIF = 0
CP_QTD_ESTACAS_EDIF = 0

'AÇO ESTACAS
CP_CA60_4MM_EST_EDIF = 0
CP_CA50_5MM_EST_EDIF = 0
CP_CA50_6MM_EST_EDIF = 0
CP_CA50_8MM_EST_EDIF = 0
CP_CA50_10MM_EST_EDIF = 0
CP_CA50_12MM_EST_EDIF = 0
CP_CA50_16MM_EST_EDIF = 0
CP_CA60_5MM_EST_EDIF = 0
CP_CONCR_EST_EDIF = 0

'AÇO SAPATAS
CP_CA60_4MM_SAP_EDIF = 0
CP_CA50_5MM_SAP_EDIF = 0
CP_CA50_6MM_SAP_EDIF = 0
CP_CA50_8MM_SAP_EDIF = 0
CP_CA50_10MM_SAP_EDIF = 0
CP_CA50_12MM_SAP_EDIF = 0
CP_CA50_16MM_SAP_EDIF = 0
CP_CA60_5MM_SAP_EDIF = 0
CP_CONCR_SAP_EDIF = 0

'AÇO ARRANQUES
CP_CA60_4MM_ARR_EDIF = 0
CP_CA50_5MM_ARR_EDIF = 0
CP_CA50_6MM_ARR_EDIF = 0
CP_CA50_8MM_ARR_EDIF = 0
CP_CA50_10MM_ARR_EDIF = 0
CP_CA50_12MM_ARR_EDIF = 0
CP_CA50_16MM_ARR_EDIF = 0
CP_CA60_5MM_ARR_EDIF = 0
CP_CONCR_ARR_EDIF = 0

'AÇO BALDRAMES
CP_CA60_4MM_BALD_EDIF = 0
CP_CA50_5MM_BALD_EDIF = 0
CP_CA50_6MM_BALD_EDIF = 0
CP_CA50_8MM_BALD_EDIF = 0
CP_CA50_10MM_BALD_EDIF = 0
CP_CA50_12MM_BALD_EDIF = 0
CP_CA50_16MM_BALD_EDIF = 0
CP_CA60_5MM_BALD_EDIF = 0
CP_CONCR_BALD_EDIF = 0

'AÇO COLUNAS TÉRREO
CP_CA60_4MM_COLUNA_TERREO_EDIF = 0
CP_CA50_5MM_COLUNA_TERREO_EDIF = 0
CP_CA50_6MM_COLUNA_TERREO_EDIF = 0
CP_CA50_8MM_COLUNA_TERREO_EDIF = 0
CP_CA50_10MM_COLUNA_TERREO_EDIF = 0
CP_CA50_12MM_COLUNA_TERREO_EDIF = 0
CP_CA50_16MM_COLUNA_TERREO_EDIF = 0
CP_CA60_5MM_COLUNA_TERREO_EDIF = 0
CP_CONCR_COLUNA_TERREO_EDIF = 0

'CAIXARIAS PILARES TÉRREO
CP_COLUNAS_15_TERREO_EDIF = 0
CP_COLUNAS_20_TERREO_EDIF = 0
CP_COLUNAS_30_TERREO_EDIF = 0
CP_AREA_FORMA_COLUNA_MAIOR_25CM = O

'AÇO VIGA RESPALDO TÉRREO
CP_CA60_4MM_COLUNA_TERREO_EDIF = 0
CP_CA50_5MM_COLUNA_TERREO_EDIF = 0
CP_CA50_6MM_COLUNA_TERREO_EDIF = 0
CP_CA50_8MM_COLUNA_TERREO_EDIF = 0
CP_CA50_10MM_COLUNA_TERREO_EDIF = 0
CP_CA50_12MM_COLUNA_TERREO_EDIF = 0
CP_CA50_16MM_COLUNA_TERREO_EDIF = 0
CP_CA60_5MM_COLUNA_TERREO_EDIF = 0
CP_CONCR_COLUNA_TERREO_EDIF = 0
CP_CONCR_VIGA_RESPALDO_TERREO_EDIF = 0

'LAJE TÉRREO
CP_TIPO_LOJE_TERREO_EDIF = ""
CP_RESIST_CONCRETO_LOJE_TERREO_EDIF = ""

'AÇO COLUNAS PAV_1
CP_CA60_4MM_COLUN_PAV_1_EDIF = 0
CP_CA50_5MM_COLUN_PAV_1_EDIF = 0
CP_CA50_6MM_COLUN_PAV_1_EDIF = 0
CP_CA50_8MM_COLUN_PAV_1_EDIF = 0
CP_CA50_10MM_COLUN_PAV_1_EDIF = 0
CP_CA50_12MM_COLUN_PAV_1_EDIF = 0
CP_CA50_16MM_COLUN_PAV_1_EDIF = 0
CP_CA60_5MM_COLUN_PAV_1_EDIF = 0
CP_CONCR_COLUN_PAV_1_EDIF = 0

'CAIXARIAS PAV_1
CP_COLUNAS_15_PAV_1_EDIF = 0
CP_COLUNAS_20_PAV_1_EDIF = 0
CP_COLUNAS_25_PAV_1_EDIF = 0
CP_AREA_FORMA_COLUNA_PAV_1_MAIOR_25CM = 0

'AÇO VIGAS PAV_1
CP_CA60_4MM_VIGA_RESPALDO_PAV_1_EDIF = 0
CP_CA50_5MM_VIGA_RESPALDO_PAV_1_EDIF = 0
CP_CA50_6MM_VIGA_RESPALDO_PAV_1_EDIF = 0
CP_CA50_8MM_VIGA_RESPALDO_PAV_1_EDIF = 0
CP_CA50_10MM_VIGA_RESPALDO_PAV_1_EDIF = 0
CP_CA50_12MM_VIGA_RESPALDO_PAV_1_EDIF = 0
CP_CA50_16MM_VIGA_RESPALDO_PAV_1_EDIF = 0
CP_CA60_5MM_VIGA_RESPALDO_PAV_1_EDIF = 0
CP_VOLUME_CONCRETO_VIGA_RESPALDO_PAV_1_EDIF = 0

'LAJE PAV_1
CP_TIPO_LOJE_PAV_1_EDIF = ""
CP_RESIST_CONCRETO_LOJE_PAV_1_EDIF = ""

'COLUNAS COBERTURAS
CP_CA60_4MM_COLUNA_COBERTURA_EDIF = 0
CP_CA50_5MM_COLUNA_COBERTURA_EDIF = 0
CP_CA50_6MM_COLUNA_COBERTURA_EDIF = 0
CP_CA50_8MM_COLUNA_COBERTURA_EDIF = 0
CP_CA50_10MM_COLUNA_COBERTURA_EDIF = 0
CP_CA50_12MM_COLUNA_COBERTURA_EDIF = 0
CP_CA50_16MM_COLUNA_COBERTURA_EDIF = 0
CP_CA60_5MM_COLUNA_COBERTURA_EDIF = 0
CP_VOLUME_CONCRETO_COLUNA_RESPALDO_COBERTURA_EDIF = 0

'VIGAS COBERTURA
CP_CA60_4MM_VIGA_COBERTURA_EDIF = 0
CP_CA50_5MM_VIGA_COBERTURA_EDIF = 0
CP_CA50_6MM_VIGA_COBERTURA_EDIF = 0
CP_CA50_8MM_VIGA_COBERTURA_EDIF = 0
CP_CA50_10MM_VIGA_COBERTURA_EDIF = 0
CP_CA50_12MM_VIGA_COBERTURA_EDIF = 0
CP_CA50_16MM_VIGA_COBERTURA_EDIF = 0
CP_CA60_5MM_VIGA_COBERTURA_EDIF = 0
CP_VOLUME_CONCRETO_VIGA_RESPALDO_COBERTURA_EDIF = 0

'CAIXARIAS
CP_COLUNAS_15_COBERTURA_EDIF = 0
CP_COLUNAS_20_COBERTURA_EDIF = 0
CP_COLUNAS_25_COBERTURA_EDIF = 0
CP_AREA_FORMA_COLUNA_COBERTURA_MAIOR_25CM = 0

'ARRIMO
CP_COMPRIMENTO_ARRIMO = 0
CP_ALTURA_ARRIMO = 0
CP_NUMERO_VIGAS_ARRIMO = 0
CP_QTD_ESTACAS_ARRIMO = 0
CP_PROF_ESTACAS_ARRIMO = 0
CP_DIAMETRO_ESTACAS_ARRIMO = 0

CP_CA60_4MM_ESTACAS_ARRIMO = 0
CP_CA50_5MM_ESTACAS_ARRIMO = 0
CP_CA50_6MM_ESTACAS_ARRIMO = 0
CP_CA50_8MM_ESTACAS_ARRIMO = 0
CP_CA50_10MM_ESTACAS_ARRIMO = 0
CP_CA50_12MM_ESTACAS_ARRIMO = 0
CP_CA50_16MM_ESTACAS_ARRIMO = 0
CP_CA60_5MM_ESTACAS_ARRIMO = 0
CP_CONCR_ESTACAS_ARRIMO = 0

CP_CA60_4MM_SAPATAS_ARRIMO = 0
CP_CA50_5MM_SAPATAS_ARRIMO = 0
CP_CA50_6MM_SAPATAS_ARRIMO = 0
CP_CA50_8MM_SAPATAS_ARRIMO = 0
CP_CA50_10MM_SAPATAS_ARRIMO = 0
CP_CA50_12MM_SAPATAS_ARRIMO = 0
CP_CA50_16MM_SAPATAS_ARRIMO = 0
CP_CA60_5MM_SAPATAS_ARRIMO = 0
CP_CONCR_SAPATAS_ARRIMO = 0

CP_CA60_4MM_ARRANQUES_ARRIMO = 0
CP_CA50_5MM_ARRANQUES_ARRIMO = 0
CP_CA50_6MM_ARRANQUES_ARRIMO = 0
CP_CA50_8MM_ARRANQUES_ARRIMO = 0
CP_CA50_10MM_ARRANQUES_ARRIMO = 0
CP_CA50_12MM_ARRANQUES_ARRIMO = 0
CP_CA50_16MM_ARRANQUES_ARRIMO = 0
CP_CA60_5MM_ARRANQUES_ARRIMO = 0
CP_CONCR_ARRANQUES_ARRIMO = 0

CP_CA60_4MM_BALDRAME_ARRIMO = 0
CP_CA50_5MM_BALDRAME_ARRIMO = 0
CP_CA50_6MM_BALDRAME_ARRIMO = 0
CP_CA50_8MM_BALDRAME_ARRIMO = 0
CP_CA50_10MM_BALDRAME_ARRIMO = 0
CP_CA50_12MM_BALDRAME_ARRIMO = 0
CP_CA50_16MM_BALDRAME_ARRIMO = 0
CP_CA60_5MM_BALDRAME_ARRIMO = 0
CP_CONCR_BALDRAME_ARRIMO = 0

CP_CA60_4MM_GIGANTE_ARRIMO = 0
CP_CA50_5MM_GIGANTE_ARRIMO = 0
CP_CA50_6MM_GIGANTE_ARRIMO = 0
CP_CA50_8MM_GIGANTE_ARRIMO = 0
CP_CA50_10MM_GIGANTE_ARRIMO = 0
CP_CA50_12MM_GIGANTE_ARRIMO = 0
CP_CA50_16MM_GIGANTE_ARRIMO = 0
CP_CA60_5MM_GIGANTE_ARRIMO = 0
CP_CONCR_GIGANTE_ARRIMO = 0

CP_CA60_4MM_COLUNAS_ARRIMO = 0
CP_CA50_5MM_COLUNAS_ARRIMO = 0
CP_CA50_6MM_COLUNAS_ARRIMO = 0
CP_CA50_8MM_COLUNAS_ARRIMO = 0
CP_CA50_10MM_COLUNAS_ARRIMO = 0
CP_CA50_12MM_COLUNAS_ARRIMO = 0
CP_CA50_16MM_COLUNAS_ARRIMO = 0
CP_CA60_5MM_COLUNAS_ARRIMO = 0
CP_CONCR_COLUNAS_ARRIMO = 0

CP_CA60_4MM_VIGAS_ARRIMO = 0
CP_CA50_5MM_VIGAS_ARRIMO = 0
CP_CA50_6MM_VIGAS_ARRIMO = 0
CP_CA50_8MM_VIGAS_ARRIMO = 0
CP_CA50_10MM_VIGAS_ARRIMO = 0
CP_CA50_12MM_VIGAS_ARRIMO = 0
CP_CA50_16MM_VIGAS_ARRIMO = 0
CP_CA60_5MM_VIGAS_ARRIMO = 0
CP_CONCR_VIGAS_ARRIMO = 0

CP_RESISTENCIA_CONCRETO_ARRIMO = ""

'PISCINA
CP_AREA_CONSTRUIDA_PISCINA = 0
CP_PAREDES_M2_TOTAL_PISCINA = 0
CP_PERIMETRO_PAREDES_PISCINA = 0
CP_GABARITO_OBRA_PISCINA = 0
CP_PROFUNDIDADE_PISCINA = 0
CP_QTD_ESTACAS_PISCINA = 0
CP_DIAMETRO_ESTACAS_PISCINA = 0
CP_PROFUNDIDADE_ESTACAS_PISCINA = 0
CP_COLUNAS_15_PISCINA = 0
CP_COLUNAS_20_PISCINA = 0
CP_COLUNAS_25_PISCINA = 0
CP_AREA_FORMA_COLUNA_MAIOR_25CM_PISCINA = 0
CP_RESISTENCIA_CONCRETO_PISCINA = ""


CP_CA60_4MM_ESTACAS_PISCINA = 0
CP_CA50_5MM_ESTACAS_PISCINA = 0
CP_CA50_6MM_ESTACAS_PISCINA = 0
CP_CA50_8MM_ESTACAS_PISCINA = 0
CP_CA50_10MM_ESTACAS_PISCINA = 0
CP_CA50_12MM_ESTACAS_PISCINA = 0
CP_CA50_16MM_ESTACAS_PISCINA = 0
CP_CA60_5MM_ESTACAS_PISCINA = 0
CP_CONCR_ESTACAS_PISCINA = 0

CP_CA60_4MM_SAPATAS_PISCINA = 0
CP_CA50_5MM_SAPATAS_PISCINA = 0
CP_CA50_6MM_SAPATAS_PISCINA = 0
CP_CA50_8MM_SAPATAS_PISCINA = 0
CP_CA50_10MM_SAPATAS_PISCINA = 0
CP_CA50_12MM_SAPATAS_PISCINA = 0
CP_CA50_16MM_SAPATAS_PISCINA = 0
CP_CA60_5MM_SAPATAS_PISCINA = 0
 CP_CONCR_SAPATAS_PISCINA = 0

CP_CA60_4MM_ARRANQUES_PISCINA = 0
CP_CA50_5MM_ARRANQUES_PISCINA = 0
CP_CA50_6MM_ARRANQUES_PISCINA = 0
CP_CA50_8MM_ARRANQUES_PISCINA = 0
CP_CA50_10MM_ARRANQUES_PISCINA = 0
CP_CA50_12MM_ARRANQUES_PISCINA = 0
CP_CA50_16MM_ARRANQUES_PISCINA = 0
CP_CA60_5MM_ARRANQUES_PISCINA = 0
CP_CONCR_ARRANQUES_PISCINA = 0

CP_CA60_4MM_BALDRAME_PISCINA = 0
CP_CA50_5MM_BALDRAME_PISCINA = 0
CP_CA50_6MM_BALDRAME_PISCINA = 0
CP_CA50_8MM_BALDRAME_PISCINA = 0
CP_CA50_10MM_BALDRAME_PISCINA = 0
CP_CA50_12MM_BALDRAME_PISCINA = 0
CP_CA50_16MM_BALDRAME_PISCINA = 0
CP_CA60_5MM_BALDRAME_PISCINA = 0
CP_CONCR_BALDRAME_PISCINA = 0

CP_CA60_4MM_CONTRAPISO_PISCINA = 0
CP_CA50_5MM_CONTRAPISO_PISCINA = 0
CP_CA50_6MM_CONTRAPISO_PISCINA = 0
CP_CA50_8MM_CONTRAPISO_PISCINA = 0
CP_CA50_10MM_CONTRAPISO_PISCINA = 0
CP_CA50_12MM_CONTRAPISO_PISCINA = 0
CP_CA50_16MM_CONTRAPISO_PISCINA = 0
CP_CA60_5MM_CONTRAPISO_PISCINA = 0
CP_CONCR_CONTRAPISO_PISCINA = 0

CP_CA60_4MM_COLUNAS_PISCINA = 0
CP_CA50_5MM_COLUNAS_PISCINA = 0
CP_CA50_6MM_COLUNAS_PISCINA = 0
CP_CA50_8MM_COLUNAS_PISCINA = 0
CP_CA50_10MM_COLUNAS_PISCINA = 0
CP_CA50_12MM_COLUNAS_PISCINA = 0
CP_CA50_16MM_COLUNAS_PISCINA = 0
CP_CA60_5MM_COLUNAS_PISCINA = 0
CP_CONCR_COLUNAS_PISCINA = 0

CP_CA60_4MM_VIGAS_PISCINA = 0
CP_CA50_5MM_VIGAS_PISCINA = 0
CP_CA50_6MM_VIGAS_PISCINA = 0
CP_CA50_8MM_VIGAS_PISCINA = 0
CP_CA50_10MM_VIGAS_PISCINA = 0
CP_CA50_12MM_VIGAS_PISCINA = 0
CP_CA50_16MM_VIGAS_PISCINA = 0
CP_CA60_5MM_VIGAS_PISCINA = 0
CP_CONCR_VIGAS_PISCINA = 0



'ESQUADRIAS

 CP_ESQUADRIA_TIPO_1 = ""
 CP_ESQUADRIA_TIPO_2 = ""
 CP_ESQUADRIA_TIPO_3 = ""
 CP_ESQUADRIA_TIPO_4 = ""
 CP_ESQUADRIA_TIPO_5 = ""
 CP_ESQUADRIA_TIPO_6 = ""
 CP_ESQUADRIA_TIPO_7 = ""
 CP_ESQUADRIA_TIPO_8 = ""
 CP_ESQUADRIA_TIPO_9 = ""
 CP_ESQUADRIA_TIPO_10 = ""
 CP_ESQUADRIA_TIPO_11 = ""
 CP_ESQUADRIA_TIPO_12 = ""
 CP_ESQUADRIA_TIPO_13 = ""
 CP_ESQUADRIA_TIPO_14 = ""
 CP_ESQUADRIA_TIPO_15 = ""
 CP_ESQUADRIA_TIPO_16 = ""
 CP_ESQUADRIA_TIPO_17 = ""
 CP_ESQUADRIA_TIPO_18 = ""
 
 CP_TELA_1 = ""
 CP_TELA_2 = ""
 CP_TELA_3 = ""
 CP_TELA_4 = ""
 CP_TELA_5 = ""
 CP_TELA_6 = ""
 CP_TELA_7 = ""
 CP_TELA_8 = ""
 CP_TELA_9 = ""
 CP_TELA_10 = ""
 CP_TELA_11 = ""
 CP_TELA_12 = ""
 CP_TELA_13 = ""
 CP_TELA_14 = ""
 CP_TELA_15 = ""
 CP_TELA_16 = ""
 CP_TELA_17 = ""
 CP_TELA_18 = ""

 CP_QTD_1 = 0
 CP_QTD_2 = 0
 CP_QTD_3 = 0
 CP_QTD_4 = 0
 CP_QTD_5 = 0
 CP_QTD_6 = 0
 CP_QTD_7 = 0
 CP_QTD_8 = 0
 CP_QTD_9 = 0
 CP_QTD_10 = 0
 CP_QTD_11 = 0
 CP_QTD_12 = 0
 CP_QTD_13 = 0
 CP_QTD_14 = 0
 CP_QTD_15 = 0
 CP_QTD_16 = 0
 CP_QTD_17 = 0
 CP_QTD_18 = 0


 CP_ALTURA_1 = 0
 CP_ALTURA_2 = 0
 CP_ALTURA_3 = 0
 CP_ALTURA_4 = 0
 CP_ALTURA_5 = 0
 CP_ALTURA_6 = 0
 CP_ALTURA_7 = 0
 CP_ALTURA_8 = 0
 CP_ALTURA_9 = 0
 CP_ALTURA_10 = 0
 CP_ALTURA_11 = 0
 CP_ALTURA_12 = 0
 CP_ALTURA_13 = 0
 CP_ALTURA_14 = 0
 CP_ALTURA_15 = 0
 CP_ALTURA_16 = 0
 CP_ALTURA_17 = 0
 CP_ALTURA_18 = 0


 CP_LARGURA_1 = 0
 CP_LARGURA_2 = 0
 CP_LARGURA_3 = 0
 CP_LARGURA_4 = 0
 CP_LARGURA_5 = 0
 CP_LARGURA_6 = 0
 CP_LARGURA_7 = 0
 CP_LARGURA_8 = 0
 CP_LARGURA_9 = 0
 CP_LARGURA_10 = 0
 CP_LARGURA_11 = 0
 CP_LARGURA_12 = 0
 CP_LARGURA_13 = 0
 CP_LARGURA_14 = 0
 CP_LARGURA_15 = 0
 CP_LARGURA_16 = 0
 CP_LARGURA_17 = 0
 CP_LARGURA_18 = 0


 CP_FOLHAS_1 = 0
 CP_FOLHAS_2 = 0
 CP_FOLHAS_3 = 0
 CP_FOLHAS_4 = 0
 CP_FOLHAS_5 = 0
 CP_FOLHAS_6 = 0
 CP_FOLHAS_7 = 0
 CP_FOLHAS_8 = 0
 CP_FOLHAS_9 = 0
 CP_FOLHAS_10 = 0
 CP_FOLHAS_11 = 0
 CP_FOLHAS_12 = 0
 CP_FOLHAS_13 = 0
 CP_FOLHAS_14 = 0
 CP_FOLHAS_15 = 0
 CP_FOLHAS_16 = 0
 CP_FOLHAS_17 = 0
 CP_FOLHAS_18 = 0




On Error Resume Next

'ARQ

CP_AREA_CONSTRUIDA_EDIF = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_EDIF", Columns("A:B"), 2, False)
CP_M2_PAREDES_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_EDIF", Columns("A:B"), 2, False)
CP_M2_PAREDES_INTERNAS_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_INTERNAS_EDIF", Columns("A:B"), 2, False)
CP_M2_PAREDES_EXTERNAS_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_EXTERNAS_EDIF", Columns("A:B"), 2, False)
CP_GABARITO_EDIF = WorksheetFunction.VLookup("CP_GABARITO_EDIF", Columns("A:B"), 2, False)
CP_PERIMETRO_PAREDES_TERREO_EDIF = WorksheetFunction.VLookup("CP_PERIMETRO_PAREDES_TERREO_EDIF", Columns("A:B"), 2, False)
CP_TIPOLOGIA_EDIF = WorksheetFunction.VLookup("CP_TIPOLOGIA_EDIF", Columns("A:B"), 2, False)

'TÉRREO
CP_M2_PAREDES_15_TERREO_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_15_TERREO_EDIF", Columns("A:B"), 2, False)
CP_M2_PAREDES_20_TERREO_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_20_TERREO_EDIF", Columns("A:B"), 2, False)
CP_M2_PAREDES_25_TERREO_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_25_TERREO_EDIF", Columns("A:B"), 2, False)
CP_VAO_PORTAS_JANELAS_TERREO_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_20_TERREO_EDIF", Columns("A:B"), 2, False)
CP_AREA_M2_TERREO_EDIF = WorksheetFunction.VLookup("CP_AREA_M2_TERREO_EDIF", Columns("A:B"), 2, False)
CP_AREA_LOJE_TERREO_EDIF = WorksheetFunction.VLookup("CP_AREA_LOJE_TERREO_EDIF", Columns("A:B"), 2, False)
CP_PERIMETRO_LOJE_TERREO_EDIF = WorksheetFunction.VLookup("CP_PERIMETRO_LOJE_TERREO_EDIF", Columns("A:B"), 2, False)
CP_AREA_LOJE_MACICA_TERREO_EDIF = WorksheetFunction.VLookup("CP_AREA_LOJE_MACICA_TERREO_EDIF", Columns("A:B"), 2, False)

'PAV_1
CP_M2_PAREDES_15_PAV_1_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_15_PAV_1_EDIF", Columns("A:B"), 2, False)
CP_M2_PAREDES_20_PAV_1_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_20_PAV_1_EDIF", Columns("A:B"), 2, False)
CP_M2_PAREDES_25_PAV_1_EDIF = WorksheetFunction.VLookup("CP_M2_PAREDES_25_PAV_1_EDIF", Columns("A:B"), 2, False)
CP_VAO_PORTAS_JANELAS_PAV_1_EDIF = WorksheetFunction.VLookup("CP_VAO_PORTAS_JANELAS_PAV_1_EDIF", Columns("A:B"), 2, False)
CP_PERIMETRO_PAREDES_PAV_1_EDIF = WorksheetFunction.VLookup("CP_PERIMETRO_PAREDES_PAV_1_EDIF", Columns("A:B"), 2, False)
CP_PERIMETRO_LOJE_PAV_1_EDIF = WorksheetFunction.VLookup("CP_PERIMETRO_LOJE_PAV_1_EDIF", Columns("A:B"), 2, False)
CP_AREA_M2_PAV_1_EDIF = WorksheetFunction.VLookup("CP_AREA_M2_PAV_1_EDIF", Columns("A:B"), 2, False)

'LAJE PAV_1
CP_AREA_LOJE_PAV_1_EDIF = WorksheetFunction.VLookup("CP_AREA_LOJE_PAV_1_EDIF", Columns("A:B"), 2, False)
CP_AREA_LOJE_MACICA_PAV_1_EDIF = WorksheetFunction.VLookup("CP_AREA_LOJE_MACICA_PAV_1_EDIF", Columns("A:B"), 2, False)

'REVESTIMENTO
CP_REVESTIMENTO_INTERNO_EDIF = WorksheetFunction.VLookup("CP_REVESTIMENTO_INTERNO_EDIF", Columns("A:B"), 2, False)

'PAVIMENTAÇÃO EXTERNA
CP_PAVIMENTACAO_EXTERNA = WorksheetFunction.VLookup("CP_PAVIMENTACAO_EXTERNA", Columns("A:B"), 2, False)
CP_PERIMETRO_PAV_EXTERNA = WorksheetFunction.VLookup("CP_PERIMETRO_PAV_EXTERNA", Columns("A:B"), 2, False)

'MURO DIVISA
CP_COMPRIMENTO_MURO_DIVISA = WorksheetFunction.VLookup("CP_COMPRIMENTO_MURO_DIVISA", Columns("A:B"), 2, False)
CP_ALTURA_MURO_DIVISA = WorksheetFunction.VLookup("CP_ALTURA_MURO_DIVISA", Columns("A:B"), 2, False)

'COBERTURA
CP_COBERTURA_1_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_1_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_2_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_2_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_3_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_3_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_4_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_4_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_5_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_5_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_6_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_6_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_7_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_7_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_8_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_8_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_9_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_9_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_10_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_10_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_11_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_11_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_12_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_12_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_13_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_13_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_14_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_14_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_15_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_15_EDIF", Columns("A:B"), 2, False)
CP_COBERTURA_16_EDIF = WorksheetFunction.VLookup("CP_COBERTURA_16_EDIF", Columns("A:B"), 2, False)


CP_COMP_COBERTURA_1_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_1_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_2_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_2_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_3_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_3_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_4_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_4_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_5_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_5_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_6_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_6_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_7_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_7_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_8_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_8_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_9_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_9_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_10_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_10_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_11_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_11_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_12_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_12_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_13_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_13_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_14_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_14_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_15_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_15_EDIF", Columns("A:B"), 2, False)
CP_COMP_COBERTURA_16_EDIF = WorksheetFunction.VLookup("CP_COMP_COBERTURA_16_EDIF", Columns("A:B"), 2, False)


CP_LARG_COBERTURA_1_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_1_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_2_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_2_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_3_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_3_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_4_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_4_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_5_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_5_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_6_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_6_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_7_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_7_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_8_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_8_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_9_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_9_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_10_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_10_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_11_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_11_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_12_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_12_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_13_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_13_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_14_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_14_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_15_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_15_EDIF", Columns("A:B"), 2, False)
CP_LARG_COBERTURA_16_EDIF = WorksheetFunction.VLookup("CP_LARG_COBERTURA_16_EDIF", Columns("A:B"), 2, False)


CP_AGUAS_COBERTURA_1_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_1_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_2_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_2_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_3_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_3_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_4_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_4_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_5_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_5_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_6_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_6_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_7_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_7_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_8_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_8_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_9_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_9_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_10_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_10_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_11_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_11_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_12_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_12_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_13_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_13_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_14_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_14_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_15_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_15_EDIF", Columns("A:B"), 2, False)
CP_AGUAS_COBERTURA_16_EDIF = WorksheetFunction.VLookup("CP_AGUAS_COBERTURA_16_EDIF", Columns("A:B"), 2, False)


CP_INCL_COBERTURA_1_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_1_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_2_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_2_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_3_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_3_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_4_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_4_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_5_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_5_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_6_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_6_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_7_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_7_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_8_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_8_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_9_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_9_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_10_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_10_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_11_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_11_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_12_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_12_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_13_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_13_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_14_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_14_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_15_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_15_EDIF", Columns("A:B"), 2, False)
CP_INCL_COBERTURA_16_EDIF = WorksheetFunction.VLookup("CP_INCL_COBERTURA_16_EDIF", Columns("A:B"), 2, False)



'ENGENHARIA

CP_RESISTENCIA_CONCRETO_EDIF = WorksheetFunction.VLookup("CP_RESISTENCIA_CONCRETO_EDIF", Columns("D:E"), 2, False)
CP_DIAMETRO_ESTACAS_EDIF = WorksheetFunction.VLookup("CP_DIAMETRO_ESTACAS_EDIF", Columns("D:E"), 2, False)
CP_QTD_ESTACAS_EDIF = WorksheetFunction.VLookup("CP_QTD_ESTACAS_EDIF", Columns("D:E"), 2, False)
CP_PROF_ESTACAS_EDIF = WorksheetFunction.VLookup("CP_PROF_ESTACAS_EDIF", Columns("D:E"), 2, False)

'AÇO ESTACAS
CP_CA60_4MM_EST_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_EST_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_EST_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_EST_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_EST_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_EST_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_EST_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_EST_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_EST_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_EST_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_EST_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_EST_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_EST_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_EST_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_EST_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_EST_EDIF", Columns("D:E"), 2, False)
CP_CONCR_EST_EDIF = WorksheetFunction.VLookup("CP_CONCR_EST_EDIF", Columns("D:E"), 2, False)

'AÇO SAPATAS
CP_CA60_4MM_SAP_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_SAP_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_SAP_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_SAP_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_SAP_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_SAP_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_SAP_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_SAP_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_SAP_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_SAP_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_SAP_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_SAP_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_SAP_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_SAP_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_SAP_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_SAP_EDIF", Columns("D:E"), 2, False)
CP_CONCR_SAP_EDIF = WorksheetFunction.VLookup("CP_CONCR_SAP_EDIF", Columns("D:E"), 2, False)


'AÇO ARRANQUES
CP_CA60_4MM_ARR_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_ARR_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_ARR_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_ARR_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_ARR_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_ARR_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_ARR_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_ARR_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_ARR_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_ARR_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_ARR_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_ARR_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_ARR_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_ARR_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_ARR_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_ARR_EDIF", Columns("D:E"), 2, False)
CP_CONCR_ARR_EDIF = WorksheetFunction.VLookup("CP_CONCR_ARR_EDIF", Columns("D:E"), 2, False)


'AÇO BALDRAMES
CP_CA60_4MM_BALD_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_BALD_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_BALD_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_BALD_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_BALD_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_BALD_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_BALD_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_BALD_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_BALD_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_BALD_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_BALD_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_BALD_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_BALD_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_BALD_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_BALD_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_BALD_EDIF", Columns("D:E"), 2, False)
CP_CONCR_BALD_EDIF = WorksheetFunction.VLookup("CP_CONCR_BALD_EDIF", Columns("D:E"), 2, False)

'AÇO COLUNAS TÉRREO
CP_CA60_4MM_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CONCR_COLUNA_TERREO_EDIF = WorksheetFunction.VLookup("CP_CONCR_COLUNA_TERREO_EDIF", Columns("D:E"), 2, False)

'CAIXARIAS PILARES TÉRREO
CP_COLUNAS_15_TERREO_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_15_TERREO_EDIF", Columns("D:E"), 2, False)
CP_COLUNAS_20_TERREO_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_20_TERREO_EDIF", Columns("D:E"), 2, False)
CP_COLUNAS_30_TERREO_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_30_TERREO_EDIF", Columns("D:E"), 2, False)
CP_AREA_FORMA_COLUNA_MAIOR_25CM = WorksheetFunction.VLookup("CP_AREA_FORMA_COLUNA_MAIOR_25CM", Columns("D:E"), 2, False)

'AÇO VIGAS RESPALDO TÉRREO
CP_CA60_4MM_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)
CP_CONCR_VIGA_RESPALDO_TERREO_EDIF = WorksheetFunction.VLookup("CP_CONCR_VIGA_RESPALDO_TERREO_EDIF", Columns("D:E"), 2, False)

'LAJE TÉRREO
CP_TIPO_LOJE_TERREO_EDIF = WorksheetFunction.VLookup("CP_TIPO_LOJE_TERREO_EDIF", Columns("D:E"), 2, False)
CP_RESIST_CONCRETO_LOJE_TERREO_EDIF = WorksheetFunction.VLookup("CP_RESIST_CONCRETO_LOJE_TERREO_EDIF", Columns("D:E"), 2, False)

'AÇO COLUNAS PAV_1
CP_CA60_4MM_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CONCR_COLUN_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CONCR_COLUN_PAV_1_EDIF", Columns("D:E"), 2, False)

'CAIXARIA COLUNAS PAV_1
CP_COLUNAS_15_PAV_1_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_15_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_COLUNAS_20_PAV_1_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_20_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_COLUNAS_25_PAV_1_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_25_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_AREA_FORMA_COLUNA_PAV_1_MAIOR_25CM = WorksheetFunction.VLookup("CP_AREA_FORMA_COLUNA_PAV_1_MAIOR_25CM", Columns("D:E"), 2, False)

'VIGAS PAV_1
CP_CA60_4MM_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_VOLUME_CONCRETO_VIGA_RESPALDO_PAV_1_EDIF = WorksheetFunction.VLookup("CP_VOLUME_CONCRETO_VIGA_RESPALDO_PAV_1_EDIF", Columns("D:E"), 2, False)

'LAJE PAV_1
CP_TIPO_LOJE_PAV_1_EDIF = WorksheetFunction.VLookup("CP_TIPO_LOJE_PAV_1_EDIF", Columns("D:E"), 2, False)
CP_RESIST_CONCRETO_LOJE_PAV_1_EDIF = WorksheetFunction.VLookup("CP_RESIST_CONCRETO_LOJE_PAV_1_EDIF", Columns("D:E"), 2, False)

'COLUNAS COBERTURA
CP_CA60_4MM_COLUNA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_COLUNA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_COLUNA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_COLUNA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_COLUNA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_COLUNA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_COLUNA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_COLUNA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_COLUNA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_COLUNA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_COLUNA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_COLUNA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_COLUNA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_COLUNA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_COLUNA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_COLUNA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_VOLUME_CONCRETO_COLUNA_RESPALDO_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_VOLUME_CONCRETO_COLUNA_RESPALDO_COBERTURA_EDIF", Columns("D:E"), 2, False)

'VIGAS COBERTURA
CP_CA60_4MM_VIGA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA60_4MM_VIGA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_5MM_VIGA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_5MM_VIGA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_6MM_VIGA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_6MM_VIGA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_8MM_VIGA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_8MM_VIGA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_10MM_VIGA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_10MM_VIGA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_12MM_VIGA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_12MM_VIGA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA50_16MM_VIGA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA50_16MM_VIGA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_CA60_5MM_VIGA_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_CA60_5MM_VIGA_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_VOLUME_CONCRETO_VIGA_RESPALDO_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_VOLUME_CONCRETO_VIGA_RESPALDO_COBERTURA_EDIF", Columns("D:E"), 2, False)

'CAIXARIAS COBERTURA
CP_COLUNAS_15_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_15_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_COLUNAS_20_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_20_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_COLUNAS_25_COBERTURA_EDIF = WorksheetFunction.VLookup("CP_COLUNAS_25_COBERTURA_EDIF", Columns("D:E"), 2, False)
CP_AREA_FORMA_COLUNA_COBERTURA_MAIOR_25CM = WorksheetFunction.VLookup("CP_AREA_FORMA_COLUNA_COBERTURA_MAIOR_25CM", Columns("D:E"), 2, False)

'ARRIMO
CP_COMPRIMENTO_ARRIMO = WorksheetFunction.VLookup("CP_COMPRIMENTO_ARRIMO", Columns("M:N"), 2, False)
CP_ALTURA_ARRIMO = WorksheetFunction.VLookup("CP_ALTURA_ARRIMO", Columns("M:N"), 2, False)
CP_NUMERO_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_NUMERO_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_QTD_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_QTD_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_PROF_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_PROF_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_DIAMETRO_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_DIAMETRO_ESTACAS_ARRIMO", Columns("M:N"), 2, False)

CP_COLUNAS_15_ARRIMO = WorksheetFunction.VLookup("CP_COLUNAS_15_ARRIMO", Columns("M:N"), 2, False)
CP_COLUNAS_20_ARRIMO = WorksheetFunction.VLookup("CP_COLUNAS_20_ARRIMO", Columns("M:N"), 2, False)
CP_COLUNAS_30_ARRIMO = WorksheetFunction.VLookup("CP_COLUNAS_30_ARRIMO", Columns("M:N"), 2, False)
CP_AREA_FORMA_COLUNA_ARRIMO_MAIOR_25CM = WorksheetFunction.VLookup("CP_AREA_FORMA_COLUNA_ARRIMO_MAIOR_25CM", Columns("M:N"), 2, False)


CP_CA60_4MM_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CA60_4MM_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_5MM_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_5MM_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_6MM_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_6MM_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_8MM_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_8MM_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_10MM_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_10MM_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_12MM_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_12MM_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_16MM_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_16MM_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA60_5MM_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CA60_5MM_ESTACAS_ARRIMO", Columns("M:N"), 2, False)
CP_CONCR_ESTACAS_ARRIMO = WorksheetFunction.VLookup("CP_CONCR_ESTACAS_ARRIMO", Columns("M:N"), 2, False)

CP_CA60_4MM_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CA60_4MM_SAPATAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_5MM_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_5MM_SAPATAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_6MM_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_6MM_SAPATAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_8MM_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_8MM_SAPATAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_10MM_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_10MM_SAPATAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_12MM_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_12MM_SAPATAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_16MM_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_16MM_SAPATAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA60_5MM_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CA60_5MM_SAPATAS_ARRIMO", Columns("M:N"), 2, False)
CP_CONCR_SAPATAS_ARRIMO = WorksheetFunction.VLookup("CP_CONCR_SAPATAS_ARRIMO", Columns("M:N"), 2, False)

CP_CA60_4MM_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CA60_4MM_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_5MM_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CA50_5MM_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_6MM_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CA50_6MM_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_8MM_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CA50_8MM_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_10MM_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CA50_10MM_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_12MM_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CA50_12MM_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_16MM_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CA50_16MM_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)
CP_CA60_5MM_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CA60_5MM_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)
CP_CONCR_ARRANQUES_ARRIMO = WorksheetFunction.VLookup("CP_CONCR_ARRANQUES_ARRIMO", Columns("M:N"), 2, False)

CP_CA60_4MM_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CA60_4MM_BALDRAME_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_5MM_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CA50_5MM_BALDRAME_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_6MM_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CA50_6MM_BALDRAME_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_8MM_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CA50_8MM_BALDRAME_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_10MM_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CA50_10MM_BALDRAME_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_12MM_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CA50_12MM_BALDRAME_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_16MM_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CA50_16MM_BALDRAME_ARRIMO", Columns("M:N"), 2, False)
CP_CA60_5MM_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CA60_5MM_BALDRAME_ARRIMO", Columns("M:N"), 2, False)
CP_CONCR_BALDRAME_ARRIMO = WorksheetFunction.VLookup("CP_CONCR_BALDRAME_ARRIMO", Columns("M:N"), 2, False)

CP_CA60_4MM_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CA60_4MM_GIGANTE_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_5MM_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CA50_5MM_GIGANTE_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_6MM_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CA50_6MM_GIGANTE_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_8MM_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CA50_8MM_GIGANTE_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_10MM_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CA50_10MM_GIGANTE_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_12MM_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CA50_12MM_GIGANTE_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_16MM_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CA50_16MM_GIGANTE_ARRIMO", Columns("M:N"), 2, False)
CP_CA60_5MM_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CA60_5MM_GIGANTE_ARRIMO", Columns("M:N"), 2, False)
CP_CONCR_GIGANTE_ARRIMO = WorksheetFunction.VLookup("CP_CONCR_GIGANTE_ARRIMO", Columns("M:N"), 2, False)

CP_CA60_4MM_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CA60_4MM_COLUNAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_5MM_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_5MM_COLUNAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_6MM_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_6MM_COLUNAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_8MM_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_8MM_COLUNAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_10MM_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_10MM_COLUNAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_12MM_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_12MM_COLUNAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_16MM_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_16MM_COLUNAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA60_5MM_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CA60_5MM_COLUNAS_ARRIMO", Columns("M:N"), 2, False)
CP_CONCR_COLUNAS_ARRIMO = WorksheetFunction.VLookup("CP_CONCR_COLUNAS_ARRIMO", Columns("M:N"), 2, False)

CP_CA60_4MM_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CA60_4MM_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_5MM_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_5MM_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_6MM_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_6MM_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_8MM_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_8MM_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_10MM_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_10MM_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_12MM_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_12MM_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA50_16MM_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CA50_16MM_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_CA60_5MM_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CA60_5MM_VIGAS_ARRIMO", Columns("M:N"), 2, False)
CP_CONCR_VIGAS_ARRIMO = WorksheetFunction.VLookup("CP_CONCR_VIGAS_ARRIMO", Columns("M:N"), 2, False)

CP_RESISTENCIA_CONCRETO_ARRIMO = WorksheetFunction.VLookup("CP_RESISTENCIA_CONCRETO_ARRIMO", Columns("M:N"), 2, False)

'PISCINA
CP_AREA_CONSTRUIDA_PISCINA = WorksheetFunction.VLookup("CP_AREA_CONSTRUIDA_PISCINA", Columns("G:H"), 2, False)
CP_PAREDES_M2_TOTAL_PISCINA = WorksheetFunction.VLookup("CP_PAREDES_M2_TOTAL_PISCINA", Columns("G:H"), 2, False)
CP_PERIMETRO_PAREDES_PISCINA = WorksheetFunction.VLookup("CP_PERIMETRO_PAREDES_PISCINA", Columns("G:H"), 2, False)
CP_GABARITO_OBRA_PISCINA = WorksheetFunction.VLookup("CP_GABARITO_OBRA_PISCINA", Columns("G:H"), 2, False)
CP_PROFUNDIDADE_PISCINA = WorksheetFunction.VLookup("CP_PROFUNDIDADE_PISCINA", Columns("G:H"), 2, False)
CP_QTD_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_QTD_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_DIAMETRO_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_DIAMETRO_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_PROFUNDIDADE_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_PROFUNDIDADE_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_COLUNAS_15_PISCINA = WorksheetFunction.VLookup("CP_COLUNAS_15_PISCINA", Columns("G:H"), 2, False)
CP_COLUNAS_20_PISCINA = WorksheetFunction.VLookup("CP_COLUNAS_20_PISCINA", Columns("G:H"), 2, False)
CP_COLUNAS_25_PISCINA = WorksheetFunction.VLookup("CP_COLUNAS_25_PISCINA", Columns("G:H"), 2, False)
CP_AREA_FORMA_COLUNA_MAIOR_25CM_PISCINA = WorksheetFunction.VLookup("CP_AREA_FORMA_COLUNA_MAIOR_25CM_PISCINA", Columns("G:H"), 2, False)
CP_RESISTENCIA_CONCRETO_PISCINA = WorksheetFunction.VLookup("CP_RESISTENCIA_CONCRETO_PISCINA", Columns("G:H"), 2, False)


CP_CA60_4MM_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CA60_4MM_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_5MM_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_5MM_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_6MM_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_6MM_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_8MM_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_8MM_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_10MM_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_10MM_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_12MM_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_12MM_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_16MM_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_16MM_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_CA60_5MM_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CA60_5MM_ESTACAS_PISCINA", Columns("G:H"), 2, False)
CP_CONCR_ESTACAS_PISCINA = WorksheetFunction.VLookup("CP_CONCR_ESTACAS_PISCINA", Columns("G:H"), 2, False)

CP_CA60_4MM_SAPATAS_PISCINA = WorksheetFunction.VLookup("CP_CA60_4MM_SAPATAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_5MM_SAPATAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_5MM_SAPATAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_6MM_SAPATAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_6MM_SAPATAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_8MM_SAPATAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_8MM_SAPATAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_10MM_SAPATAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_10MM_SAPATAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_12MM_SAPATAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_12MM_SAPATAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_16MM_SAPATAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_16MM_SAPATAS_PISCINA", Columns("G:H"), 2, False)
CP_CA60_5MM_SAPATAS_PISCINA = WorksheetFunction.VLookup("CP_CA60_5MM_SAPATAS_PISCINA", Columns("G:H"), 2, False)
 CP_CONCR_SAPATAS_PISCINA = WorksheetFunction.VLookup(" CP_CONCR_SAPATAS_PISCINA", Columns("G:H"), 2, False)

CP_CA60_4MM_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CA60_4MM_ARRANQUES_PISCINA", Columns("G:H"), 2, False)
CP_CA50_5MM_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CA50_5MM_ARRANQUES_PISCINA", Columns("G:H"), 2, False)
CP_CA50_6MM_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CA50_6MM_ARRANQUES_PISCINA", Columns("G:H"), 2, False)
CP_CA50_8MM_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CA50_8MM_ARRANQUES_PISCINA", Columns("G:H"), 2, False)
CP_CA50_10MM_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CA50_10MM_ARRANQUES_PISCINA", Columns("G:H"), 2, False)
CP_CA50_12MM_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CA50_12MM_ARRANQUES_PISCINA", Columns("G:H"), 2, False)
CP_CA50_16MM_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CA50_16MM_ARRANQUES_PISCINA", Columns("G:H"), 2, False)
CP_CA60_5MM_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CA60_5MM_ARRANQUES_PISCINA", Columns("G:H"), 2, False)
CP_CONCR_ARRANQUES_PISCINA = WorksheetFunction.VLookup("CP_CONCR_ARRANQUES_PISCINA", Columns("G:H"), 2, False)

CP_CA60_4MM_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CA60_4MM_BALDRAME_PISCINA", Columns("G:H"), 2, False)
CP_CA50_5MM_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CA50_5MM_BALDRAME_PISCINA", Columns("G:H"), 2, False)
CP_CA50_6MM_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CA50_6MM_BALDRAME_PISCINA", Columns("G:H"), 2, False)
CP_CA50_8MM_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CA50_8MM_BALDRAME_PISCINA", Columns("G:H"), 2, False)
CP_CA50_10MM_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CA50_10MM_BALDRAME_PISCINA", Columns("G:H"), 2, False)
CP_CA50_12MM_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CA50_12MM_BALDRAME_PISCINA", Columns("G:H"), 2, False)
CP_CA50_16MM_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CA50_16MM_BALDRAME_PISCINA", Columns("G:H"), 2, False)
CP_CA60_5MM_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CA60_5MM_BALDRAME_PISCINA", Columns("G:H"), 2, False)
CP_CONCR_BALDRAME_PISCINA = WorksheetFunction.VLookup("CP_CONCR_BALDRAME_PISCINA", Columns("G:H"), 2, False)

CP_CA60_4MM_CONTRAPISO_PISCINA = WorksheetFunction.VLookup("CP_CA60_4MM_CONTRAPISO_PISCINA", Columns("G:H"), 2, False)
CP_CA50_5MM_CONTRAPISO_PISCINA = WorksheetFunction.VLookup("CP_CA50_5MM_CONTRAPISO_PISCINA", Columns("G:H"), 2, False)
CP_CA50_6MM_CONTRAPISO_PISCINA = WorksheetFunction.VLookup("CP_CA50_6MM_CONTRAPISO_PISCINA", Columns("G:H"), 2, False)
CP_CA50_8MM_CONTRAPISO_PISCINA = WorksheetFunction.VLookup("CP_CA50_8MM_CONTRAPISO_PISCINA", Columns("G:H"), 2, False)
CP_CA50_10MM_CONTRAPISO_PISCINA = WorksheetFunction.VLookup("CP_CA50_10MM_CONTRAPISO_PISCINA", Columns("G:H"), 2, False)
CP_CA50_12MM_CONTRAPISO_PISCINA = WorksheetFunction.VLookup("CP_CA50_12MM_CONTRAPISO_PISCINA", Columns("G:H"), 2, False)
CP_CA50_16MM_CONTRAPISO_PISCINA = WorksheetFunction.VLookup("CP_CA50_16MM_CONTRAPISO_PISCINA", Columns("G:H"), 2, False)
CP_CA60_5MM_CONTRAPISO_PISCINA = WorksheetFunction.VLookup("CP_CA60_5MM_CONTRAPISO_PISCINA", Columns("G:H"), 2, False)
CP_CONCR_GIGANTE_PISCINA = WorksheetFunction.VLookup("CP_CONCR_GIGANTE_PISCINA", Columns("G:H"), 2, False)

CP_CA60_4MM_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CA60_4MM_COLUNAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_5MM_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_5MM_COLUNAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_6MM_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_6MM_COLUNAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_8MM_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_8MM_COLUNAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_10MM_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_10MM_COLUNAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_12MM_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_12MM_COLUNAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_16MM_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_16MM_COLUNAS_PISCINA", Columns("G:H"), 2, False)
CP_CA60_5MM_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CA60_5MM_COLUNAS_PISCINA", Columns("G:H"), 2, False)
CP_CONCR_COLUNAS_PISCINA = WorksheetFunction.VLookup("CP_CONCR_COLUNAS_PISCINA", Columns("G:H"), 2, False)

CP_CA60_4MM_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CA60_4MM_VIGAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_5MM_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_5MM_VIGAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_6MM_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_6MM_VIGAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_8MM_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_8MM_VIGAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_10MM_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_10MM_VIGAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_12MM_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_12MM_VIGAS_PISCINA", Columns("G:H"), 2, False)
CP_CA50_16MM_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CA50_16MM_VIGAS_PISCINA", Columns("G:H"), 2, False)
CP_CA60_5MM_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CA60_5MM_VIGAS_PISCINA", Columns("G:H"), 2, False)
CP_CONCR_VIGAS_PISCINA = WorksheetFunction.VLookup("CP_CONCR_VIGAS_PISCINA", Columns("G:H"), 2, False)

'ESQUADRIAS

 CP_ESQUADRIA_TIPO_1 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_1", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_2 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_2", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_3 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_3", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_4 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_4", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_5 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_5", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_6 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_6", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_7 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_7", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_8 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_8", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_9 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_9", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_10 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_10", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_11 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_11", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_12 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_12", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_13 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_13", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_14 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_14", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_15 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_15", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_16 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_16", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_17 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_17", Columns("T:AA"), 2, False)
 CP_ESQUADRIA_TIPO_18 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_18", Columns("T:AA"), 2, False)
 
 
 CP_TELA_1 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_1", Columns("T:AA"), 4, False)
 CP_TELA_2 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_2", Columns("T:AA"), 4, False)
 CP_TELA_3 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_3", Columns("T:AA"), 4, False)
 CP_TELA_4 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_4", Columns("T:AA"), 4, False)
 CP_TELA_5 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_5", Columns("T:AA"), 4, False)
 CP_TELA_6 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_6", Columns("T:AA"), 4, False)
 CP_TELA_7 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_7", Columns("T:AA"), 4, False)
 CP_TELA_8 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_8", Columns("T:AA"), 4, False)
 CP_TELA_9 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_9", Columns("T:AA"), 4, False)
 CP_TELA_10 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_10", Columns("T:AA"), 4, False)
 CP_TELA_11 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_11", Columns("T:AA"), 4, False)
 CP_TELA_12 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_12", Columns("T:AA"), 4, False)
 CP_TELA_13 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_13", Columns("T:AA"), 4, False)
 CP_TELA_14 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_14", Columns("T:AA"), 4, False)
 CP_TELA_15 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_15", Columns("T:AA"), 4, False)
 CP_TELA_16 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_16", Columns("T:AA"), 4, False)
 CP_TELA_17 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_17", Columns("T:AA"), 4, False)
 CP_TELA_18 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_18", Columns("T:AA"), 4, False)

 
 
 CP_QTD_1 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_1", Columns("T:AA"), 5, False)
 CP_QTD_2 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_2", Columns("T:AA"), 5, False)
 CP_QTD_3 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_3", Columns("T:AA"), 5, False)
 CP_QTD_4 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_4", Columns("T:AA"), 5, False)
 CP_QTD_5 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_5", Columns("T:AA"), 5, False)
 CP_QTD_6 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_6", Columns("T:AA"), 5, False)
 CP_QTD_7 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_7", Columns("T:AA"), 5, False)
 CP_QTD_8 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_8", Columns("T:AA"), 5, False)
 CP_QTD_9 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_9", Columns("T:AA"), 5, False)
 CP_QTD_10 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_10", Columns("T:AA"), 5, False)
 CP_QTD_11 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_11", Columns("T:AA"), 5, False)
 CP_QTD_12 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_12", Columns("T:AA"), 5, False)
 CP_QTD_13 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_13", Columns("T:AA"), 5, False)
 CP_QTD_14 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_14", Columns("T:AA"), 5, False)
 CP_QTD_15 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_15", Columns("T:AA"), 5, False)
 CP_QTD_16 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_16", Columns("T:AA"), 5, False)
 CP_QTD_17 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_17", Columns("T:AA"), 5, False)
 CP_QTD_18 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_18", Columns("T:AA"), 5, False)



 CP_ALTURA_1 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_1", Columns("T:AA"), 6, False)
 CP_ALTURA_2 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_2", Columns("T:AA"), 6, False)
 CP_ALTURA_3 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_3", Columns("T:AA"), 6, False)
 CP_ALTURA_4 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_4", Columns("T:AA"), 6, False)
 CP_ALTURA_5 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_5", Columns("T:AA"), 6, False)
 CP_ALTURA_6 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_6", Columns("T:AA"), 6, False)
 CP_ALTURA_7 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_7", Columns("T:AA"), 6, False)
 CP_ALTURA_8 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_8", Columns("T:AA"), 6, False)
 CP_ALTURA_9 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_9", Columns("T:AA"), 6, False)
 CP_ALTURA_10 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_10", Columns("T:AA"), 6, False)
 CP_ALTURA_11 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_11", Columns("T:AA"), 6, False)
 CP_ALTURA_12 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_12", Columns("T:AA"), 6, False)
 CP_ALTURA_13 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_13", Columns("T:AA"), 6, False)
 CP_ALTURA_14 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_14", Columns("T:AA"), 6, False)
 CP_ALTURA_15 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_15", Columns("T:AA"), 6, False)
 CP_ALTURA_16 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_16", Columns("T:AA"), 6, False)
 CP_ALTURA_17 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_17", Columns("T:AA"), 6, False)
 CP_ALTURA_18 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_18", Columns("T:AA"), 6, False)



 CP_LARGURA_1 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_1", Columns("T:AA"), 7, False)
 CP_LARGURA_2 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_2", Columns("T:AA"), 7, False)
 CP_LARGURA_3 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_3", Columns("T:AA"), 7, False)
 CP_LARGURA_4 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_4", Columns("T:AA"), 7, False)
 CP_LARGURA_5 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_5", Columns("T:AA"), 7, False)
 CP_LARGURA_6 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_6", Columns("T:AA"), 7, False)
 CP_LARGURA_7 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_7", Columns("T:AA"), 7, False)
 CP_LARGURA_8 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_8", Columns("T:AA"), 7, False)
 CP_LARGURA_9 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_9", Columns("T:AA"), 7, False)
 CP_LARGURA_10 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_10", Columns("T:AA"), 7, False)
 CP_LARGURA_11 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_11", Columns("T:AA"), 7, False)
 CP_LARGURA_12 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_12", Columns("T:AA"), 7, False)
 CP_LARGURA_13 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_13", Columns("T:AA"), 7, False)
 CP_LARGURA_14 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_14", Columns("T:AA"), 7, False)
 CP_LARGURA_15 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_15", Columns("T:AA"), 7, False)
 CP_LARGURA_16 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_16", Columns("T:AA"), 7, False)
 CP_LARGURA_17 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_17", Columns("T:AA"), 7, False)
 CP_LARGURA_18 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_18", Columns("T:AA"), 7, False)



 CP_FOLHAS_1 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_1", Columns("T:AA"), 8, False)
 CP_FOLHAS_2 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_2", Columns("T:AA"), 8, False)
 CP_FOLHAS_3 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_3", Columns("T:AA"), 8, False)
 CP_FOLHAS_4 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_4", Columns("T:AA"), 8, False)
 CP_FOLHAS_5 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_5", Columns("T:AA"), 8, False)
 CP_FOLHAS_6 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_6", Columns("T:AA"), 8, False)
 CP_FOLHAS_7 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_7", Columns("T:AA"), 8, False)
 CP_FOLHAS_8 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_8", Columns("T:AA"), 8, False)
 CP_FOLHAS_9 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_9", Columns("T:AA"), 8, False)
 CP_FOLHAS_10 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_10", Columns("T:AA"), 8, False)
 CP_FOLHAS_11 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_11", Columns("T:AA"), 8, False)
 CP_FOLHAS_12 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_12", Columns("T:AA"), 8, False)
 CP_FOLHAS_13 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_13", Columns("T:AA"), 8, False)
 CP_FOLHAS_14 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_14", Columns("T:AA"), 8, False)
 CP_FOLHAS_15 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_15", Columns("T:AA"), 8, False)
 CP_FOLHAS_16 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_16", Columns("T:AA"), 8, False)
 CP_FOLHAS_17 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_17", Columns("T:AA"), 8, False)
 CP_FOLHAS_18 = WorksheetFunction.VLookup("CP_ESQUADRIA_TIPO_18", Columns("T:AA"), 8, False)





On Error GoTo 0


End Sub

